Repository PrideInLondon/pride-london-web, pull requests merged in 2019-07, with the labels that each got.

#689 Deep linking for app
  .well-known/apple-app-site-association
Labels: Event Details, Mobile, New Feature, size/S

#690 Deep linking path fix
  static/.well-known/apple-app-site-association
Labels: Event Details, Mobile, New Feature, size/S

#694 Deep linking - AASA fix
  .well-known/apple-app-site-association
  static/.well-known/apple-app-site-association
Labels: Event Details, Mobile, New Feature, size/S

#704 Android native app prompt
  gatsby-config.js
  package.json
  src/layouts/index.js
  static/icon-192.png
  static/icon-512.png
  static/manifest.json
  yarn.lock
Labels: Improvement, Mobile

#698 Add fallback text for when a venue doesn't specify a11y details
  src/features/exploreLondon/components/communityPartnerCard/index.js
  src/pages/explore-london.js
Labels: Improvement, Refactoring, Visitor Information, size/M

#711 Footer changes
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/_spec.js
  src/components/footer/index.js
  src/components/footer/styles.js
Labels: Navigation, Refactoring, size/M

#709 iOS app prompt on every site
  src/layouts/index.js
  src/pages/events.js
Labels: Mobile, Refactoring, size/M

#721 Homepage app promo section
  src/features/homepage/components/downloadAppBox/__snapshots__/_spec.js.snap
  src/features/homepage/components/downloadAppBox/_spec.js
  src/features/homepage/components/downloadAppBox/index.js
  src/features/homepage/components/downloadAppBox/styles.js
  src/pages/index.js
  src/theme/assets/images/i-phone-mockup.png
Labels: Homepage, Improvement, Refactoring

#723 Download our app - mockup image swapped
  src/theme/assets/images/i-phone-mockup.png
Labels: Bug, Mobile, QA, Refactoring

#724 Download app section swapped
  src/features/homepage/components/downloadAppBox/__snapshots__/_spec.js.snap
  src/features/homepage/components/downloadAppBox/index.js
  src/features/homepage/components/downloadAppBox/styles.js
  src/pages/index.js
Labels: Improvement, Mobile, QA, Refactoring

#733 Linter fixes
  src/components/navigation/submenu/index.js
  src/components/newsCardHeader/index.js
  src/components/newsMetrics/index.js
  src/features/blog/components/featuredArticle/index.js
  src/features/blog/components/newsCard/index.js
  src/features/blog/components/viewsCard/index.js
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blogDetails/components/blogHeader/index.js
  src/features/blogDetails/containers/pageHeader/index.js
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/_spec.js
  src/features/homepage/components/latestNews/index.js
  src/pages/news-and-views.js
  src/pages/parade/groups.js
  yarn.lock
Labels: Refactoring, size/XL

#725 Event card dates
  src/features/events/components/eventInfoCard.js
  src/features/events/helpers/_spec.js
  src/features/events/helpers/index.js
  src/features/events/tests/_mocks.js
  src/features/events/tests/eventInfoCard_spec.js
Labels: Event, Event Details, Improvement, Refactoring, size/S

#688 Sharing functionality
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/icons/email.js
  src/components/icons/linkedin.js
  src/components/icons/messenger.js
  src/features/blogDetails/components/socialList/__snapshots__/_spec.js.snap
  src/features/events/components/eventShareSection.js
  src/features/events/index.js
  src/features/events/tests/eventShareSection_spec.js
  src/layouts/index.js
  src/templates/event.js
Labels: Improvement, New Component, New Feature, Refactoring, size/L

#736 Moment formatting event date fix
  src/features/events/components/eventInfoCard.js
  src/features/events/helpers/index.js
Labels: Bug, Refactoring, size/XS

#730 Featured events updates
  src/features/events/helpers/_spec.js
  src/features/events/helpers/index.js
  src/features/homepage/components/featuredEvents/featuredEventsQuery.js
Labels: Event, Improvement, New Feature, Refactoring, size/M

#741 LGTM fixes
  src/components/appContext/index.js
  src/features/events/filters/eventDropdownFilter.js
  src/features/help/components/dropDown.js
  src/templates/event.js
Labels: Bug, Improvement, Refactoring, size/S

#742 Recurrence event page fix
  gatsby-node.js
  src/features/events/helpers/index.js
Labels: Bug, Event, Event Details, QA, size/S

#749 Rainbow planet redirect
  static/_redirects
Labels: Navigation, size/XS

#747 Sponsor logos size
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/components/footer/styles.js
  src/components/sponsors/components/sponsorBadge/__snapshots__/_spec.js.snap
  src/components/sponsors/components/sponsorBadge/styles.js
Labels: Improvement, QA, Sponsors, size/L

#751 SonarCloud fixes
  src/features/blogDetails/components/blogContent/renderMethods.js
  src/features/genericContentPage/renderMethods.js
  src/layouts/index.css
  src/pages/privacy.js
Labels: Bug, Improvement, Refactoring, size/S

#757 Explore London - address line 2 fix
  src/features/exploreLondon/components/communityPartnerCard/index.js
Labels: Bug, Refactoring, Visitor Information, size/XS

#759 Homepage - featured events
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/index.js
  src/features/homepage/components/featuredEvents/slickSettings.js
  src/features/homepage/components/featuredEvents/styles.js
Labels: Bug, Refactoring, size/S

#760 Homepage sections fix
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/featuredEventsQuery.js
  src/features/homepage/components/featuredEvents/index.css
  src/features/homepage/components/featuredEvents/index.js
  src/features/homepage/components/featuredEvents/slickSettings.js
  src/features/homepage/components/featuredEvents/styles.js
Labels: Bug, Refactoring, size/S

#766 Hide app promos
  src/layouts/index.js
  src/pages/index.js
Labels: Homepage, Mobile, Refactoring, size/S

#810 Homepage featured recurrence events
  src/features/homepage/components/featuredEvents/featuredEventsQuery.js
Labels: Bug, Event, Refactoring, size/M

#815 homepage banner changes
  src/pages/index.js
  src/theme/assets/images/banners/home/video-poster.jpg
Labels: Homepage, Refactoring

#816 Help keep Pride free button
  src/pages/index.js
Labels: Refactoring, size/S

#838 Removed line up section from main navigation
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Improvement, Navigation, Refactoring, size/M

#839 Added an overflow to the event filter dropdown
  src/features/events/filters/eventDropdownFilter.js
Labels: Event, QA, Refactoring, size/XS
