Repository PrideInLondon/pride-london-web, pull requests merged in 2019-06, with the labels that each got.

#512 Fix duplicate parade group
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
Labels: Hotfix, Parade Groups, size/XS

#522 Fix broken redirect for RBL
  static/_redirects
Labels: Hotfix, Navigation, size/XS

#532 Update Merchandise navigation URL
  src/components/button/index.js
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/features/genericContentPage/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  yarn.lock
Labels: Navigation, Refactoring, size/XS

#533 Cookie Banner
  .env.example
  .eslintrc.js
  gatsby-config.js
  package.json
  src/components/cookieNotice/__snapshots__/_spec.js.snap
  src/components/cookieNotice/_spec.js
  src/components/cookieNotice/index.js
  src/components/icons/closeIcon.js
  src/layouts/index.js
  yarn.lock
Labels: New Component, New Feature, SEO, size/L

#536 Sort recurring events
  src/components/appContext/index.js
Labels: Improvement, Refactoring, size/S

#537 Feature/cookie
  src/components/cookieNotice/__snapshots__/_spec.js.snap
  src/components/cookieNotice/index.js
  src/layouts/index.js
Labels: Bug, Refactoring, SEO, size/L

#542 Fix alphabet letters and groups sizes
  src/features/paradeGroups/components/letterLink/styles.js
  src/features/paradeGroups/components/paradeGroup/styles.js
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/styles.js
Labels: Bug, Parade Groups, size/L

#544 Footer partner links added
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/components/footer/styles.js
Labels: Improvement, Navigation, SEO, size/L

#549 Related events view fix
  src/features/events/components/eventsYouMayLike.js
Labels: Bug, Event Details, QA, size/XS

#548 Parade group icons order
  src/features/paradeGroups/components/paradeGroup/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/paradeGroup/index.js
  src/pages/parade-groups.js
Labels: Bug, Parade Groups, QA, size/M

#550 Add Festival link to Nav
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Navigation, size/XS

#564 Shop redirects
  static/_redirects
Labels: SEO, size/XS

#563 Change copy of cookie policy
  src/components/cookieNotice/__snapshots__/_spec.js.snap
  src/components/cookieNotice/index.js
Labels: Improvement, Refactoring, SEO, size/S

#562 Sticky letters menu
  src/features/blog/containers/viewsContainer/styles.js
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/styles.js
  src/features/paradeGroups/components/letterLink/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/letterLink/_spec.js
  src/features/paradeGroups/components/letterLink/index.js
  src/features/paradeGroups/components/letterLink/styles.js
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/_spec.js
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/layouts/index.css
  src/layouts/index.js
Labels: Parade Groups, QA, size/L

#556 Spacing between parade groups and headers
  src/features/paradeGroups/components/letterGroup/styles.js
  src/features/paradeGroups/components/paradeGroup/styles.js
Labels: Parade Groups, QA, size/XS

#575 ReadTime proptype, renderMethod return fix
  src/components/newsCardHeader/index.js
  src/components/newsMetrics/index.js
  src/features/blog/components/newsCard/index.js
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/index.js
  src/features/genericContentPage/renderMethods.js
Labels: Bug, Improvement, QA, Refactoring, size/XS

#573 Banner image fix
  src/templates/genericContentPage.js
Labels: Bug, Homepage, QA, size/XS

#574 Alphabetise the category and accessibility filter list
  src/components/checkboxSet/_spec.js
  src/components/checkboxSet/index.js
  src/features/events/components/eventsFilters.js
  src/features/events/filters/eventDropdownFilter.js
Labels: Event, Improvement, Refactoring, size/M

#578 Add stalls page to stalls menu
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Navigation, SEO, size/XS

#582 Bug on homepage slider
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/slickSettings.js
  src/features/homepage/components/featuredEvents/styles.js
Labels: Bug, Homepage, size/S

#580 Sponsor badge background color section
  src/features/sponsors/components/sponsorBadge/styles.js
Labels: Refactoring, Sponsors, size/XS

#581 Expiry date for cookie banner
  src/components/cookieNotice/index.js
Labels: Improvement, Refactoring, SEO, size/L

#588 Parade groups filter label added
  src/features/paradeGroups/containers/paradeGroupsFiltersContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsFiltersContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsFiltersContainer/styles.js
Labels: Bug, Parade Groups, QA, Refactoring, size/S

#592 Content indentation removed, subheading changed
  src/pages/parade-groups.js
Labels: Bug, Parade Groups, QA, Refactoring, size/XS

#589 Disabled letter links fix
  src/features/paradeGroups/components/letterLink/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/letterLink/index.js
  src/features/paradeGroups/components/letterLink/styles.js
Labels: Bug, Parade Groups, QA, Refactoring, size/S

#590 Parade Groups name color changed
  src/features/paradeGroups/components/paradeGroup/styles.js
Labels: Bug, Parade Groups, QA, Refactoring, size/XS

#591 Scrolling alphabet design fix
  src/features/paradeGroups/components/letterLink/styles.js
  src/features/paradeGroups/containers/paradeGroupsContainer/styles.js
Labels: Bug, Parade Groups, QA, Refactoring, size/XS

#596 Parade groups text added
  src/pages/parade-groups.js
Labels: Parade Groups, QA, size/S

#599 Update redirects and nav
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  static/_redirects
Labels: Homepage, SEO, size/M

#602 Remove nav link
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Homepage, Navigation, SEO, size/XS

#603 Update links in nav menu
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/components/navigation/submenu/styles.js
  yarn.lock
Labels: Navigation, Refactoring, SEO, size/M

#598 Hide cookie banner dismiss button
  src/components/cookieNotice/__snapshots__/_spec.js.snap
  src/components/cookieNotice/index.js
Labels: Homepage, QA, SEO, size/M

#613 Banner image changed, subheading changed
  src/pages/events.js
  src/theme/assets/images/banners/events/bg.jpg
  src/theme/assets/images/banners/events/bg@2x.jpg
  src/theme/assets/images/banners/events/bg@3x.jpg
Labels: Improvement, Refactoring

#614 Partner with us banner image changed
  src/pages/support-us/partners.js
  src/theme/assets/images/banners/sponsors/bg.jpg
  src/theme/assets/images/banners/sponsors/bg@2x.jpg
  src/theme/assets/images/banners/sponsors/bg@3x.jpg
Labels: Improvement, Refactoring

#618 Partner with us copy changed
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Refactoring, Sponsors, size/XS

#619 Gatsby Image Banners
  src/components/banner/bannerImage/__snapshots__/_spec.js.snap
  src/components/banner/bannerImage/_spec.js
  src/components/banner/bannerImage/index.js
  src/components/banner/bannerImage/styles.js
  src/templates/genericContentPage.js
  src/theme/media.js
Labels: Homepage, Improvement, Refactoring, size/XXL

#615 Embed forms based on button URL
  gatsby-node.js
  package.json
  src/features/genericContentPage/__snapshots__/_spec.js.snap
  src/features/genericContentPage/_mocks.js
  src/features/genericContentPage/_spec.js
  src/features/genericContentPage/renderMethods.js
  yarn.lock
Labels: Improvement, New Component, New Feature, Refactoring, size/XL

#635 Update menu links in nav bar
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Improvement, Navigation, QA, Refactoring, size/XS

#636 Support new parade group model
  src/constants/index.js
  src/features/paradeGroups/components/paradeGroup/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/paradeGroup/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsFiltersContainer/index.js
  src/features/paradeGroups/paradeGroupFilterPropType.js
  src/pages/parade-groups.js
Labels: Parade Groups, Refactoring, size/L

#633 Added Intercom component
  package.json
  src/components/intercom/index.js
  src/pages/support-us/partners.js
  yarn.lock
Labels: New Component, New Feature, size/M

#637 Gatsby image banners
  src/layouts/index.js
  src/templates/event.js
  src/templates/genericContentPage.js
Labels: Improvement, Refactoring, size/M

#638 Gatsby image banners
  src/features/blogDetails/components/blogHeader/_spec.js
  src/features/blogDetails/components/blogHeader/styles.js
  src/features/blogDetails/containers/pageHeader/__snapshots__/_spec.js.snap
  src/features/blogDetails/containers/pageHeader/_spec.js
  src/features/blogDetails/containers/pageHeader/index.js
  src/features/blogDetails/containers/pageHeader/styles.js
  src/templates/blogDetails.js
  src/templates/event.js
Labels: Improvement, Refactoring, size/L

#639 Add Intercom on every pages
  src/layouts/index.js
  src/pages/support-us/partners.js
Labels: New Component, New Feature, Refactoring, size/XS

#616 Parade map
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/pages/parade/map/__snapshots__/_spec.js.snap
  src/pages/parade/map/_spec.js
  src/pages/parade/map/index.js
  src/theme/assets/images/apple.svg
  src/theme/assets/images/google-play.svg
Labels: Improvement, Navigation, New Component, New Feature, size/L

#659 [QA] Footer logos IE fix
  src/components/footer/styles.js
Labels: QA, Refactoring, Sponsors, size/XS

#579 Uncomment parade groups
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/constants/index.js
  src/features/paradeGroups/components/paradeGroup/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/paradeGroup/_spec.js
  src/features/paradeGroups/components/paradeGroup/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/_spec.js
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsFiltersContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsFiltersContainer/_spec.js
  src/features/paradeGroups/containers/paradeGroupsFiltersContainer/index.js
  src/features/paradeGroups/paradeGroupFilterPropType.js
  src/pages/parade-groups.js
Labels: Parade Groups, size/M

#665 Vimeo banner
  package.json
  src/components/banner/bannerImage/_spec.js
  src/components/banner/bannerImage/index.js
  src/components/banner/bannerImage/styles.js
  src/pages/index.js
  src/theme/assets/images/banners/home/video-poster.jpg
Labels: Homepage, New Component, New Feature

#668 Refactor parade/groups navigation
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/pages/parade/groups.js
  static/_redirects
Labels: Improvement, Navigation, Refactoring, SEO, size/S

#670 IE fixes
  src/pages/parade/map/__snapshots__/_spec.js.snap
  src/pages/parade/map/_spec.js
  src/pages/parade/map/index.js
Labels: Improvement, Refactoring, size/S

#669 Ability to add sponsors to event/generic content page
  gatsby-node.js
  src/components/sponsors/components/sponsorBadge/__snapshots__/_spec.js.snap
  src/components/sponsors/components/sponsorBadge/_mocks.js
  src/components/sponsors/components/sponsorBadge/_spec.js
  src/components/sponsors/components/sponsorBadge/index.js
  src/components/sponsors/components/sponsorBadge/styles.js
  src/components/sponsors/components/sponsorSubsection/__snapshots__/_spec.js.snap
  src/components/sponsors/components/sponsorSubsection/_mocks.js
  src/components/sponsors/components/sponsorSubsection/_spec.js
  src/components/sponsors/components/sponsorSubsection/index.js
  src/components/sponsors/components/sponsorSubsection/styles.js
  src/components/sponsors/helpers/_mocks.js
  src/components/sponsors/helpers/_spec.js
  src/components/sponsors/helpers/index.js
  src/constants/index.js
  src/features/genericContentPage/__snapshots__/_spec.js.snap
  src/features/genericContentPage/_mocks.js
  src/features/genericContentPage/_spec.js
  src/features/genericContentPage/renderMethods.js
  src/features/sponsors/components/sponsorBadge/__snapshots__/_spec.js.snap
  src/features/sponsors/components/sponsorBadge/_mocks.js
  src/features/sponsors/components/sponsorBadge/_spec.js
  src/features/sponsors/components/sponsorSubsection/__snapshots__/_spec.js.snap
  src/features/sponsors/helpers/index.js
  src/pages/support-us/partners.js
  src/templates/event.js
Labels: Event, Generic Content, Improvement, New Component, Refactoring

#672 GTM cookie consent changed
  src/components/cookieNotice/_spec.js
  src/components/cookieNotice/index.js
Labels: Improvement, Refactoring, SEO, size/S

#675 Line up - Family Area added
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Navigation, Refactoring, size/XS

#677 Footer changes
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/_spec.js
  src/components/footer/index.js
  src/components/footer/styles.js
Labels: Improvement, QA, Refactoring, size/M

#681 News&Views microdata fix
  src/templates/blogDetails.js
Labels: Improvement, SEO, size/S

#682 [QA] Partner with us page - spacing fix
  src/pages/support-us/partners.js
Labels: QA, Refactoring, Sponsors, size/XS

#683 Parade Map PDF link
  src/pages/parade/map/__snapshots__/_spec.js.snap
  src/pages/parade/map/index.js
Labels: Navigation, Refactoring, SEO, size/S

#684 Fix bug onload for mobile
  src/components/banner/bannerImage/index.js
  src/components/banner/bannerImage/styles.js
Labels: Bug, Improvement, Refactoring, size/S
