Repository PrideInLondon/pride-london-web, pull requests merged in 2019-05, with the labels that each got.

#381 [MVP] [QA] SEO - Change Description #380
  src/layouts/index.js
  src/pages/events/whats-on.js
Labels: Event, QA, Refactoring, size/XS

#382 Responsive images
  gatsby-config.js
  package.json
  src/features/homepage/components/announcementCard/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementCard/_spec.js
  src/features/homepage/components/announcementCard/index.js
  src/features/homepage/components/announcementCard/styles.js
  src/features/homepage/containers/announcementsContainer/index.js
  src/utilities/index.js
  yarn.lock
Labels: Improvement, Refactoring, size/L

#388 [MVP] [QA] Homepage - Featured Events
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/_mocks.js
  src/features/homepage/components/featuredEvents/_spec.js
  src/features/homepage/components/featuredEvents/featuredEventsQuery.js
  src/features/homepage/components/featuredEvents/index.js
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/L

#389 News Card Link
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/index.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
Labels: Blog, Refactoring, size/S

#392 Hero banner copy + link
  src/pages/index.js
Labels: Homepage, Refactoring, size/XS

#371 MVP [QA #222] Volunteer Section - Replace pixelated images
  src/theme/assets/images/volunteer-bg-mobile.jpg
  src/theme/assets/images/volunteer-bg.jpg
Labels: Homepage, QA, Refactoring

#401 Replace cupcake lorem by copy in menu
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Improvement, Navigation, Refactoring, size/S

#402 [QA2] Blog Page #399
  src/components/banner/bannerImage/__snapshots__/_spec.js.snap
  src/components/banner/bannerImage/index.js
  src/components/banner/bannerImage/styles.js
  src/features/blog/components/newsCard/styles.js
  src/features/blog/containers/viewsContainer/index.js
  src/pages/blog.js
Labels: Blog, QA, Refactoring, size/L

#405 Fix donate link for navigation
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Navigation, QA, Refactoring, size/XS

#407 [QA2] Blog Detail Page #394
  src/features/blogDetails/components/blogContent/styles.js
  src/features/blogDetails/components/blogFooter/__snapshots__/_spec.js.snap
  src/features/blogDetails/components/blogFooter/index.js
  src/features/blogDetails/components/blogFooter/styles.js
  src/features/blogDetails/components/blogHeader/styles.js
  src/features/events/components/eventTagList.js
  src/templates/event.js
Labels: Blog Details, QA, Refactoring, size/M

#408 [QA2] Sponsors Page #397
  src/pages/support-us/partners.js
Labels: QA, Refactoring, Sponsors, size/XS

#406 Gatsby image for Views carousel
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/index.js
  src/features/blog/components/viewsCard/styles.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/_mocks.js
  src/pages/blog.js
Labels: Homepage, Improvement, Refactoring, size/M

#409 [QA2] Generic Page #393
  src/layouts/index.css
  src/templates/genericContentPage.js
Labels: Generic Content, QA, Refactoring, size/S

#412 [QA2] Events Page #398
  src/pages/events/whats-on.js
Labels: Event, QA, Refactoring, size/S

#414 [QA2] Homepage #400
  gatsby-config.js
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/_spec.js
  src/features/blog/components/viewsCard/index.js
  src/features/blog/components/viewsCard/styles.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/_mocks.js
  src/features/homepage/components/announcementCard/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementCard/index.js
  src/features/homepage/components/announcementCard/styles.js
  src/features/homepage/components/announcementHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementHeader/index.js
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/M

#415 Add favicons & fix partners sections
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/favicon.ico
  src/layouts/index.js
  src/pages/privacy.js
  src/pages/support-us/partners.js
  src/theme/assets/images/favicons/apple-touch-icon-114x114.png
  src/theme/assets/images/favicons/apple-touch-icon-120x120.png
  src/theme/assets/images/favicons/apple-touch-icon-144x144.png
  src/theme/assets/images/favicons/apple-touch-icon-152x152.png
  src/theme/assets/images/favicons/apple-touch-icon-57x57.png
  src/theme/assets/images/favicons/apple-touch-icon-60x60.png
  src/theme/assets/images/favicons/apple-touch-icon-72x72.png
  src/theme/assets/images/favicons/apple-touch-icon-76x76.png
  src/theme/assets/images/favicons/favicon-128x128.png
  src/theme/assets/images/favicons/favicon-16x16.png
  src/theme/assets/images/favicons/favicon-196x196.png
  src/theme/assets/images/favicons/favicon-32x32.png
  src/theme/assets/images/favicons/favicon-96x96.png
  src/theme/assets/images/favicons/favicon.ico
  src/theme/assets/images/favicons/mstile-144x144.png
  src/theme/assets/images/favicons/mstile-150x150.png
  src/theme/assets/images/favicons/mstile-310x150.png
  src/theme/assets/images/favicons/mstile-310x310.png
  src/theme/assets/images/favicons/mstile-70x70.png
Labels: Improvement, Refactoring, Sponsors

#419 Feature/add sponsor level
  src/components/banner/bannerSubtitle/styles.js
  src/constants/index.js
  src/features/homepage/components/donateSectionHeader/styles.js
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/_spec.js
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/components/latestNews/styles.js
  src/features/homepage/containers/announcementsContainer/index.js
  src/features/homepage/containers/latestNewsContainer/index.js
  src/features/homepage/containers/latestNewsContainer/styles.js
  src/pages/blog.js
  src/pages/support-us/partners.js
Labels: Improvement, Refactoring, Sponsors, size/L

#420 Menu bar links & copy
  package.json
  src/components/button/_spec.js
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/features/homepage/components/announcementHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementHeader/index.js
  src/pages/blog.js
  src/pages/events.js
  src/pages/index.js
  src/pages/support-us/partners.js
Labels: Improvement, Navigation, Refactoring, size/M

#421 Organisation Schema & Event Schema
  gatsby-config.js
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/index.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/layouts/index.js
  src/pages/blog.js
  src/templates/event.js
  src/theme/assets/images/pride-logo-social.png
Labels: Improvement, SEO

#423 Update links within README
  README.md
Labels: Documentation, Improvement, size/XS

#424 Navigation wording adjustments
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Navigation, Refactoring, size/S

#425 Fix news and views filename
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/pages/news-and-views.js
Labels: Navigation, Refactoring

#426 Fix featured events
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/components/navigation/nav/styles.js
  src/features/events/components/eventListingCard.js
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/_mocks.js
  src/features/homepage/components/featuredEvents/featuredEventsQuery.js
  src/layouts/index.js
Labels: Homepage, Refactoring, size/M

#427 Add link to partnership packages doc
  src/pages/support-us/partners.js
Labels: Refactoring, Sponsors, size/XS

#428 Navigation external urls
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/components/navigation/submenu/__snapshots__/_spec.js.snap
  src/components/navigation/submenu/index.js
  src/features/homepage/components/announcementCard/__snapshots__/_spec.js.snap
  src/utilities/index.js
Labels: Navigation, Refactoring, size/L

#429 Redirects fix
  static/_redirects
Labels: Navigation, Refactoring, size/L

#431 Footer contact link
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/components/footer/styles.js
Labels: Navigation, Refactoring, size/S

#436 add redirects and remove greyscale on footer logos
  src/components/footer/styles.js
  static/_redirects
Labels: Improvement, Navigation, size/XS

#438 Implement Security Headers
  static/_headers
Labels: Improvement, Security, size/XS

#443 [QA #442] Organise Views by Date Published
  src/pages/news-and-views.js
Labels: Blog, Improvement, size/XS

#446 Sort sponsors alphabetically
  src/pages/support-us/partners.js
Labels: Generic Content, Improvement, size/XS

#447 Update navigation copy
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
Labels: Improvement, Navigation, size/S

#457 Add redirect for /jubilee
  static/_redirects
Labels: Improvement, Navigation, size/XS

#461 media-centre redirects
  static/_redirects
Labels: Navigation, Refactoring, size/XS

#462 Remove legacy Help page
  src/pages/help.js
Labels: Bug, Refactoring, size/M

#471 Add Sitemap plugin
  gatsby-config.js
  package.json
  yarn.lock
Labels: New Feature, SEO, size/M

#480 Create letter links and container for parade groups
  src/features/paradeGroups/components/letterLink/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/letterLink/_spec.js
  src/features/paradeGroups/components/letterLink/index.js
  src/features/paradeGroups/components/letterLink/styles.js
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/_spec.js
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/styles.js
  src/pages/parade-groups.js
Labels: New Component, New Feature, Parade Groups, size/L

#487 Refactoring banner image
  src/components/grid/index.js
  src/components/navigation/navItem/styles.js
  src/layouts/index.css
  src/layouts/index.js
Labels: Improvement, Refactoring, size/M

#488 Add groups/navigation to groups for each letter
  src/features/paradeGroups/components/letterGroup/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/letterGroup/_spec.js
  src/features/paradeGroups/components/letterGroup/index.js
  src/features/paradeGroups/components/letterGroup/styles.js
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/styles.js
Labels: New Component, New Feature, Parade Groups, size/L

#491 Add parade group component with social icons
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/icons/facebook.js
  src/components/icons/globe.js
  src/components/icons/instagram.js
  src/components/icons/twitter.js
  src/features/blogDetails/components/socialList/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/letterGroup/styles.js
  src/features/paradeGroups/components/letterLink/styles.js
  src/features/paradeGroups/components/paradeGroup/__snapshots__/_spec.js.snap
  src/features/paradeGroups/components/paradeGroup/_spec.js
  src/features/paradeGroups/components/paradeGroup/index.js
  src/features/paradeGroups/components/paradeGroup/styles.js
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/styles.js
  src/pages/parade-groups.js
Labels: New Component, New Feature, Parade Groups, size/L

#493 fix z-index of latest news so img doesn't go behind sitewrapper
  src/features/homepage/containers/latestNewsContainer/styles.js
Labels: Homepage, Refactoring, size/XS

#494 Update redirects to point to the 2019 documents
  static/_redirects
Labels: Bug, Navigation, size/XS

#495 Remove scrolling container
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/styles.js
Labels: Parade Groups, Refactoring, size/L

#502 Hide parade groups page
  src/pages/parade-groups.js
Labels: Hotfix, Parade Groups, size/M

#509 Fix test warning
  src/features/paradeGroups/containers/paradeGroupsContainer/__snapshots__/_spec.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/_spec.js
Labels: Hotfix, Refactoring, size/XS
