Repository PrideInLondon/pride-london-web, pull requests merged in 2019-12, with the labels that each got.

#1169 WER-21: Add Jest to precommit hook
  package.json
Labels: Refactoring, size/XS

#1180 SEO-6: update tiles and description in listed sub tickets
  src/components/navigation/nav/__snapshots__/index.test.js.snap
  src/components/navigation/nav/index.js
  src/pages/events.js
  src/templates/genericContentPage.js
Labels: SEO, size/M

#1161 WER-25 Convert Checkbox component from classic component to use hooks
  src/components/checkbox/__snapshots__/index.test.js.snap
  src/components/checkbox/index.js
  src/components/checkbox/index.test.js
Labels: Refactoring, size/M

#1192 EVE-2 event url rewrite for SEO optimisation
  .eslintrc.js
  gatsby-node.js
  package.json
  src/components/appContext/index.js
  src/features/events/components/eventListingCard.js
  src/features/events/helpers/index.js
  src/features/events/helpers/index.test.js
  src/features/homepage/components/featuredEvents/featuredEventsQuery.js
  yarn.lock
Labels: Event, SEO, size/L

#1167 EVE-3: Update Events Page Header Content
  src/components/navigation/nav/__snapshots__/index.test.js.snap
  src/components/navigation/nav/index.js
  src/pages/events.js
Labels: Event, size/XS

#1204 WER-38 Added functionality to toggle between prod/preview content on local
  .env.example
  README.md
  gatsby-config.js
Labels: Refactoring, size/M

#1210 WER-40 update pre commit to include markdown formatter
  .remarkrc
  README.md
  SECURITY.md
  package.json
  yarn.lock
Labels: Refactoring, size/XL

#1194 WER-9: Storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/tsconfig.json
  .storybook/webpack.config.js
  package.json
  src/components/ctaLink/CTALink.stories.tsx
  src/components/ctaLink/CTALink.test.js
  src/components/ctaLink/CTALink.tsx
  src/components/ctaLink/CTALink.types.ts
  src/components/ctaLink/__snapshots__/CTALink.test.js.snap
  src/components/ctaLink/index.tsx
  src/components/filteredPagedCardContainer/__snapshots__/index.test.js.snap
  src/components/footer/__snapshots__/index.test.js.snap
  src/components/pagedCardContainer/__snapshots__/index.test.js.snap
  src/features/blogDetails/components/blogContent/__snapshots__/index.test.js.snap
  src/features/blogDetails/components/blogContent/index.test.js
  src/features/events/index.js
  src/features/genericContentPage/__snapshots__/index.test.js.snap
  src/features/genericContentPage/index.test.js
  src/layouts/index.css
  src/layouts/index.js
  src/layouts/index.styles.js
  src/utilities/index.ts
  yarn.lock
Labels: Refactoring
