Repository PrideInLondon/pride-london-web, pull requests merged in 2019-11, with the labels that each got.

#1142 WER-20 Update node version to 10
  .circleci/config.yml
  .nvmrc
Labels: size/M

#1146 WER-34 Updated event template to functional component
  src/templates/event.js
Labels: Event, Refactoring, size/L

#1145 WER-35 Updated generic content page to functional component
  src/templates/genericContentPage.js
Labels: Generic Content, Refactoring, size/M

#1141 SEO-15: Update metadata for /
  gatsby-config.js
Labels: size/XS

#1143 Feature/wer 12 implement typescript
  .babelrc
  .eslintrc.js
  config/jest.setup.js
  gatsby-config.js
  jest.config.js
  package.json
  src/components/banner/bannerImage/index.js
  src/components/ctaLink/index.tsx
  src/components/filterContainer/filterLabel/__snapshots__/index.test.js.snap
  src/components/filterContainer/index.js
  src/components/filteredPagedCardContainer/__snapshots__/index.test.js.snap
  src/components/filteredPagedCardContainer/index.js
  src/components/footer/__snapshots__/index.test.js.snap
  src/components/navigation/navItem/index.js
  src/components/pagedCardContainer/__snapshots__/index.test.js.snap
  src/components/sponsors/components/sponsorBadge/__snapshots__/index.test.js.snap
  src/features/genericContentPage/__snapshots__/index.test.js.snap
  src/features/genericContentPage/components/video/__snapshots__/index.test.js.snap
  src/features/genericContentPage/components/video/index.js
  src/features/homepage/components/featuredEvents/__snapshots__/index.test.js.snap
  src/features/paradeGroups/containers/paradeGroupsContainer/index.js
  src/pages/privacy.js
  src/utilities/index.ts
  tsconfig.json
  yarn.lock
Labels: Refactoring

#1168 WER-37: Add Stylelint configuration and precommit hook
  package.json
  stylelint.config.js
  yarn.lock
Labels: Refactoring, size/XL
