Repository PrideInLondon/pride-london-web, pull requests merged in 2019-04, with the labels that each got.

#162 Navigation Menu Update
  src/components/nav/__snapshots__/_spec.js.snap
  src/components/nav/_spec.js
  src/components/nav/index.js
  src/components/submenu/__snapshots__/_spec.js.snap
  src/components/submenu/index.js
  src/components/submenu/styles.js
Labels: Improvement, Navigation

#172 Extract input styles
  src/components/input/index.js
  src/components/input/styles.js
Labels: Improvement, Refactoring, size/M

#178 Banner
  src/components/bannerDate/__snapshots__/_spec.js.snap
  src/components/bannerDate/_spec.js
  src/components/bannerDate/index.js
  src/components/bannerSubtitle/index.js
  src/components/bannerTitle/__snapshots__/_spec.js.snap
  src/components/bannerTitle/_spec.js
  src/components/bannerTitle/index.js
  src/components/button/__snapshots__/_spec.js.snap
  src/components/button/index.js
  src/components/imageBanner/__snapshots__/_spec.js.snap
  src/components/imageBanner/_spec.js
  src/components/imageBanner/index.js
  src/pages/index.js
  src/theme/assets/images/banners/home/bg.jpg
  src/theme/assets/images/banners/home/bg@2x.jpg
  src/theme/assets/images/banners/home/bg@3x.jpg
  yarn.lock
Labels: Homepage, New Component, New Feature

#174 Extract footer styles
  src/components/footer/index.js
  src/components/footer/styles.js
Labels: Improvement, Refactoring, size/L

#179 Latest News section
  src/features/blog/components/newsDate/styles.js
  src/features/blog/components/newsFilter/styles.js
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/_spec.js
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/components/latestNews/latestNewsCard/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/latestNewsCard/_spec.js
  src/features/homepage/components/latestNews/latestNewsCard/index.js
  src/features/homepage/components/latestNews/latestNewsCard/styles.js
  src/features/homepage/components/latestNews/latestNewsHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/latestNewsHeader/_spec.js
  src/features/homepage/components/latestNews/latestNewsHeader/index.js
  src/features/homepage/components/latestNews/latestNewsHeader/styles.js
  src/features/homepage/components/latestNews/styles.js
  src/features/homepage/containers/latestNewsContainer/index.js
  src/features/homepage/containers/latestNewsContainer/styles.js
  src/pages/index.js
Labels: Homepage, New Component, New Feature, size/L

#160 Featured Events section
  package-lock.json
  package.json
  src/components/button/index.js
  src/components/imageBanner/index.js
  src/configuration/jest.config.js
  src/features/events/components/eventListingCard.js
  src/features/home/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/home/components/featuredEvents/_spec.js
  src/features/home/components/featuredEvents/index.js
  src/features/home/components/featuredEvents/styles.js
  src/pages/index.js
  src/theme/assets/images/featured-events-bg-left.png
  src/theme/assets/images/featured-events-bg-right.png
  src/theme/settingSlickSlider.js
  yarn.lock
Labels: Homepage, New Component, New Feature

#161 Volunteer section
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/_spec.js
  src/features/homepage/components/featuredEvents/index.js
  src/features/homepage/components/featuredEvents/styles.js
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/_spec.js.snap
  src/features/homepage/components/volunteerBoxInfo/_spec.js
  src/features/homepage/components/volunteerBoxInfo/index.js
  src/features/homepage/components/volunteerBoxInfo/styles.js
  src/features/homepage/containers/latestNewsContainer/styles.js
  src/pages/index.js
  src/theme/assets/images/bg-figure-volunteer.jpg
  src/theme/assets/images/volunteer-bg-mobile.jpg
  src/theme/assets/images/volunteer-bg.jpg
Labels: Homepage, New Feature

#196 Banner Hotfix
  src/components/imageBanner/__snapshots__/_spec.js.snap
  src/components/imageBanner/index.js
  src/features/home/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/home/components/featuredEvents/_spec.js
  src/features/home/components/featuredEvents/index.js
  src/features/home/components/featuredEvents/styles.js
  src/pages/index.js
Labels: Bug, Hotfix, Refactoring

#191 Footer
  src/components/ctaLink/__snapshots__/_spec.js.snap
  src/components/ctaLink/_spec.js
  src/components/ctaLink/index.js
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/_mocks.js
  src/components/footer/_spec.js
  src/components/footer/footerQuery.js
  src/components/footer/index.js
  src/components/footer/styles.js
  src/components/icons/facebook.js
  src/components/icons/instagram.js
  src/components/icons/linkedin.js
  src/components/icons/snapchat.js
  src/components/icons/twitter.js
  src/components/icons/youtube.js
  src/components/submenu/styles.js
  src/features/sponsors/components/sponsorSubsection/index.js
  src/layouts/index.js
Labels: Navigation, New Component, size/XXL

#197 Sponsors
  src/constants/index.js
  src/features/sponsors/components/sponsorBadge/index.js
  src/features/sponsors/components/sponsorSubsection/index.js
  src/pages/sponsors.js
Labels: Improvement, Sponsors, size/S

#198 Generic pages layout
  src/components/ctaLink/index.js
  src/components/footer/styles.js
  src/components/nav/index.js
  src/components/navItem/index.js
  src/components/submenu/styles.js
  src/features/events/components/eventListingCard.js
  src/layouts/index.css
  src/templates/genericContentPage.js
Labels: Generic Content, Improvement, size/M

#199 [Hotfix] Props name and delete duplicate Home folder
  src/features/events/components/eventListingCard.js
  src/features/events/tests/__snapshots__/eventsYouMayLike_spec.js.snap
  src/features/home/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/home/components/featuredEvents/_spec.js
  src/features/home/components/featuredEvents/index.js
  src/features/home/components/featuredEvents/styles.js
  src/features/homepage/components/featuredEvents/index.js
  src/pages/index.js
Labels: Hotfix, Refactoring, size/L

#200 Redirects
  gatsby-node.js
  src/pages/support-us/sponsors.js
  static/_redirects
Labels: Navigation, New Component, New Feature, size/M

#202 Feature/stop crawlers
  gatsby-config.js
  package-lock.json
  package.json
  yarn.lock
Labels: Improvement, New Feature, size/L

#205 Feature/redirects
  static/_redirects
Labels: Navigation, New Component, New Feature, size/M

#206 Footer
  gatsby-config.js
  src/components/ctaLink/__snapshots__/_spec.js.snap
  src/components/ctaLink/index.js
  src/components/footer/styles.js
  static/_redirects
Labels: Navigation, Refactoring, size/S

#204 Announcements
  src/features/homepage/components/announcementCard/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementCard/_spec.js
  src/features/homepage/components/announcementCard/index.js
  src/features/homepage/components/announcementCard/styles.js
  src/features/homepage/components/announcementHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementHeader/_spec.js
  src/features/homepage/components/announcementHeader/index.js
  src/features/homepage/components/announcementHeader/styles.js
  src/features/homepage/containers/announcementsContainer/index.js
  src/pages/index.js
Labels: Homepage, New Component, New Feature, size/L

#234 [QA #212] Partners Section - Sponsors order
  package-lock.json
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/footerQuery.js
  src/components/footer/index.js
  src/theme/assets/images/banners/bg.jpg
  src/theme/assets/images/banners/couple@2x.jpg
  src/theme/assets/images/banners/couple@3x.jpg
Labels: QA, Refactoring, Sponsors

#245 News to article
  gatsby-node.js
  src/components/newsCardHeader/__snapshots__/_spec.js.snap
  src/components/newsCardHeader/_spec.js
  src/components/newsCardHeader/index.js
  src/components/newsCardHeader/styles.js
  src/components/newsCategory/__snapshots__/_spec.js.snap
  src/components/newsCategory/_spec.js
  src/components/newsCategory/index.js
  src/components/newsCategory/styles.js
  src/components/newsMetrics/__snapshots__/_spec.js.snap
  src/components/newsMetrics/_spec.js
  src/components/newsMetrics/index.js
  src/components/newsMetrics/styles.js
  src/features/blog/components/featuredArticle/index.js
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/_spec.js
  src/features/blog/components/newsCard/index.js
  src/features/blog/components/newsCard/styles.js
  src/features/blog/components/newsDate/styles.js
  src/features/blog/components/viewsCard/_spec.js
  src/features/blog/components/viewsCard/index.js
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blog/containers/viewsContainer/index.js
  src/features/blogDetails/components/author/__snapshots__/_spec.js.snap
  src/features/blogDetails/components/author/_spec.js
  src/features/blogDetails/components/author/index.js
  src/features/blogDetails/components/blogFooter/index.js
  src/features/blogDetails/components/blogFooter/styles.js
  src/features/blogDetails/components/blogHeader/__snapshots__/_spec.js.snap
  src/features/blogDetails/components/blogHeader/_spec.js
  src/features/blogDetails/components/blogHeader/index.js
  src/features/blogDetails/components/blogHeader/styles.js
  src/features/blogDetails/components/otherArticlesHeader/styles.js
  src/features/blogDetails/containers/otherArticles/_mocks.js
  src/features/blogDetails/containers/otherArticles/_spec.js
  src/features/blogDetails/containers/otherArticles/index.js
  src/features/blogDetails/containers/pageContent/__snapshots__/_spec.js.snap
  src/features/blogDetails/containers/pageContent/_spec.js
  src/features/blogDetails/containers/pageContent/index.js
  src/features/blogDetails/containers/pageFooter/__snapshots__/_spec.js.snap
  src/features/blogDetails/containers/pageFooter/_spec.js
  src/features/blogDetails/containers/pageFooter/index.js
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/_spec.js
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/components/latestNews/latestNewsCard/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/latestNewsCard/_spec.js
  src/features/homepage/components/latestNews/latestNewsCard/index.js
  src/features/homepage/components/latestNews/latestNewsCard/styles.js
  src/features/homepage/components/latestNews/styles.js
  src/features/homepage/containers/latestNewsContainer/index.js
  src/features/homepage/containers/latestNewsContainer/styles.js
  src/pages/blog.js
  src/templates/blogDetails.js
Labels: Blog, Refactoring, size/XL

#244 Donate section
  src/components/button/__snapshots__/_spec.js.snap
  src/components/button/index.js
  src/features/homepage/components/donateSection/__snapshots__/_spec.js.snap
  src/features/homepage/components/donateSection/_spec.js
  src/features/homepage/components/donateSection/donateButtonsGroup/__snapshots__/_spec.js.snap
  src/features/homepage/components/donateSection/donateButtonsGroup/_spec.js
  src/features/homepage/components/donateSection/donateButtonsGroup/index.js
  src/features/homepage/components/donateSection/donateButtonsGroup/styles.js
  src/features/homepage/components/donateSection/index.js
  src/features/homepage/components/donateSection/styles.js
  src/features/homepage/components/donateSectionHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/donateSectionHeader/_spec.js
  src/features/homepage/components/donateSectionHeader/index.js
  src/features/homepage/components/donateSectionHeader/styles.js
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/_spec.js.snap
  src/features/homepage/containers/donateContainer/index.js
  src/features/homepage/containers/donateContainer/styles.js
  src/pages/index.js
  src/theme/assets/images/bg-donate-left.svg
  src/theme/assets/images/bg-donate-right.svg
  src/theme/assets/images/bg-mobile-donate-right.svg
Labels: Homepage, New Feature, size/XL

#247 [QA #218] Header - Add duotone image
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/components/imageBanner/index.js
  src/pages/events.js
  src/pages/support-us/sponsors.js
  src/theme/assets/images/banners/bg.jpg
  src/theme/assets/images/banners/couple@2x.jpg
  src/theme/assets/images/banners/couple@3x.jpg
  src/theme/assets/images/banners/events/bg.jpg
  src/theme/assets/images/banners/events/bg@2x.jpg
  src/theme/assets/images/banners/events/bg@3x.jpg
  src/theme/assets/images/banners/sponsors/bg.jpg
  src/theme/assets/images/banners/sponsors/bg@2x.jpg
  src/theme/assets/images/banners/sponsors/bg@3x.jpg
Labels: Navigation, QA, Refactoring

#251 [QA #238] Partners Section - No border bottom
  src/pages/support-us/sponsors.js
Labels: QA, Refactoring, Sponsors, size/XS

#250 [QA #240] Partners Section - Banner H2
  src/components/banner/bannerSubtitle/styles.js
  src/components/banner/bannerTitle/styles.js
Labels: QA, Refactoring, Sponsors, size/XS

#255 Pagination for blog
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/blog/containers/newsCards/_spec.js
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blog/containers/newsContainer/styles.js
Labels: Blog, New Component, size/L

#248 [QA #221] Volunteer Section - Refactor button to match design
  src/components/button/index.js
  src/features/homepage/components/donateSection/donateButtonsGroup/styles.js
  src/features/homepage/components/donateSection/styles.js
Labels: Homepage, QA, Refactoring, size/XS

#256 [QA #219] Volunteer Section - Shapes should be 2x images
  src/features/homepage/components/volunteerBoxInfo/styles.js
  src/theme/assets/images/bg-figure-volunteer.jpg
  src/theme/assets/images/volunteer-shapes.svg
Labels: Homepage, QA, Refactoring

#261 [QA #211] Partners Section - Update year to 2019
  src/pages/support-us/sponsors.js
Labels: QA, Refactoring, Sponsors, size/XS

#262 [QA #236] Partners Section - Body copy
  src/pages/support-us/sponsors.js
Labels: QA, Refactoring, Sponsors, size/S

#263 [QA #217] Footer - Company number link
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
Labels: Navigation, QA, Refactoring, size/S

#264 [QA #209] Partners Section - Email us button
  src/pages/support-us/sponsors.js
Labels: Navigation, QA, Refactoring, size/XS

#267 [QA #235] Partners Section - Background color
  src/features/sponsors/components/sponsorBadge/index.js
  src/layouts/index.css
  src/pages/events.js
  src/templates/genericContentPage.js
Labels: QA, Refactoring, Sponsors, size/S

#268 [QA #215] Footer - Remove third hashtag
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
Labels: Navigation, QA, Refactoring, size/S

#273 [QA #227] Generic Content Page - Missing image captions
  src/features/genericContentPage/__snapshots__/_spec.js.snap
  src/features/genericContentPage/_spec.js
  src/features/genericContentPage/components/figure/__snapshots__/_spec.js.snap
  src/features/genericContentPage/components/figure/_spec.js
  src/features/genericContentPage/components/figure/index.js
  src/features/genericContentPage/components/figure/styles.js
  src/features/genericContentPage/index.js
  src/features/genericContentPage/renderMethods.js
  src/features/sponsors/components/sponsorBadge/__snapshots__/_spec.js.snap
  src/features/sponsors/components/sponsorBadge/_spec.js
  src/features/sponsors/components/sponsorBadge/index.js
  src/templates/genericContentPage.js
Labels: Generic Content, QA, Refactoring, size/L

#275 [QA #210] Partners Section - Logo
  src/features/sponsors/components/sponsorBadge/index.js
Labels: QA, Refactoring, Sponsors, size/XS

#276 [QA #211] Partners Section - Update year to 2019 (static)
  src/pages/support-us/sponsors.js
Labels: QA, Refactoring, Sponsors, size/XS

#279 Navigation - Update Menu
  src/components/banner/bannerDate/styles.js
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/components/footer/styles.js
  src/components/nav/__snapshots__/_spec.js.snap
  src/components/nav/index.js
  src/components/navItem/index.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/genericContentPage/renderMethods.js
  src/theme/theme.js
Labels: Navigation, Refactoring, size/L

#280 [QA #274] Partners Section - Logos x4 not x3
  src/pages/support-us/sponsors.js
Labels: QA, Refactoring, Sponsors, size/XS

#281 Button and Embedded Video in Generic content page
  src/features/genericContentPage/components/video/__snapshots__/_spec.js.snap
  src/features/genericContentPage/components/video/_spec.js
  src/features/genericContentPage/components/video/index.js
  src/features/genericContentPage/components/video/styles.js
  src/features/genericContentPage/renderMethods.js
Labels: Generic Content, Refactoring, size/M

#316 [QA #305] Footer - Add #
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
Labels: Navigation, QA, Refactoring, size/S

#302 Navigation - Fix bugs
  src/components/nav/__snapshots__/_spec.js.snap
  src/components/nav/index.js
  src/components/navItem/__snapshots__/_spec.js.snap
  src/components/navItem/index.js
  src/components/submenu/__snapshots__/_spec.js.snap
  src/components/submenu/_spec.js
  src/components/submenu/index.js
  src/features/genericContentPage/__snapshots__/_spec.js.snap
  src/features/genericContentPage/_mocks.js
  src/features/genericContentPage/_spec.js
  src/features/genericContentPage/components/video/index.js
  src/features/genericContentPage/components/video/styles.js
  src/features/genericContentPage/renderMethods.js
  src/layouts/index.css
  src/pages/support-us/partners.js
  src/templates/genericContentPage.js
  static/_redirects
Labels: Navigation, Refactoring, size/L

#317 [QA #296] Homepage - Featured events spelling mistakes
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/XS

#315 [QA #310] Homepage - Donation header
  src/features/homepage/components/donateSectionHeader/styles.js
Labels: Homepage, QA, Refactoring, size/XS

#318 [QA #318] Blog Details - Share links
  src/features/blogDetails/components/socialList/__snapshots__/_spec.js.snap
  src/features/blogDetails/components/socialList/index.js
Labels: Blog Details, QA, Refactoring, size/M

#321 [QA #312] Partners Section - Header image
  src/components/banner/bannerImage/styles.js
Labels: QA, Refactoring, Sponsors, size/XS

#322 [QA #311] Homepage - Title line height
  src/components/banner/bannerDate/styles.js
  src/components/banner/bannerSubtitle/styles.js
  src/components/banner/bannerTitle/styles.js
Labels: Homepage, QA, Refactoring

#319 [Refactoring] Navigation components architecture
  src/components/navItem/_spec.js
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/_spec.js
  src/components/navigation/nav/index.js
  src/components/navigation/nav/styles.js
  src/components/navigation/navItem/__snapshots__/_spec.js.snap
  src/components/navigation/navItem/_mocks.js
  src/components/navigation/navItem/_spec.js
  src/components/navigation/navItem/index.js
  src/components/navigation/navItem/styles.js
  src/components/navigation/submenu/__snapshots__/_spec.js.snap
  src/components/navigation/submenu/_mocks.js
  src/components/navigation/submenu/_spec.js
  src/components/navigation/submenu/index.js
  src/components/navigation/submenu/styles.js
  src/components/submenu/_spec.js
  src/layouts/index.js
Labels: Improvement, Refactoring, size/XL

#320 [Refactoring] Sponsors features architecture
  src/features/sponsors/components/sponsorBadge/__snapshots__/_spec.js.snap
  src/features/sponsors/components/sponsorBadge/_mocks.js
  src/features/sponsors/components/sponsorBadge/_spec.js
  src/features/sponsors/components/sponsorBadge/index.js
  src/features/sponsors/components/sponsorBadge/styles.js
  src/features/sponsors/components/sponsorSubsection/__snapshots__/_spec.js.snap
  src/features/sponsors/components/sponsorSubsection/_mocks.js
  src/features/sponsors/components/sponsorSubsection/_spec.js
  src/features/sponsors/components/sponsorSubsection/index.js
  src/features/sponsors/components/sponsorSubsection/styles.js
Labels: Improvement, Refactoring, size/L

#323 [Refactoring] Banners
  package.json
  src/components/banner/bannerDate/styles.js
  src/components/banner/bannerImage/__snapshots__/_spec.js.snap
  src/components/banner/bannerImage/index.js
  src/components/banner/bannerImage/styles.js
  src/components/banner/bannerSubtitle/styles.js
  src/components/banner/bannerTitle/styles.js
  src/features/blog/containers/viewsContainer/styles.js
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/_spec.js
  src/features/homepage/components/featuredEvents/index.js
  src/features/homepage/components/featuredEvents/styles.js
  src/pages/blog.js
  src/pages/index.js
  src/theme/assets/images/banners/blog/bg.svg
  src/theme/settingSlickSlider.js
  yarn.lock
Labels: Homepage, Refactoring, size/L

#252 Navigation
  src/components/ctaLink/index.js
  src/features/blog/containers/viewsContainer/index.js
Labels: Navigation, Refactoring, size/XS

#324 [QA #303] Blog - All articles selector
  src/components/newsCardHeader/index.js
  src/components/newsCategory/index.js
  src/constants/index.js
  src/features/blog/components/newsFilter/__snapshots__/_spec.js.snap
  src/features/blog/components/newsFilter/index.js
  src/features/blog/components/newsFilter/styles.js
  src/features/blog/containers/filtersContainer/index.js
  src/features/blogDetails/containers/otherArticles/_spec.js
  src/features/blogDetails/containers/otherArticles/index.js
  src/features/blogDetails/containers/pageFooter/__snapshots__/_spec.js.snap
  src/features/blogDetails/containers/pageFooter/_spec.js
  src/features/blogDetails/containers/pageFooter/index.js
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/components/latestNews/styles.js
  src/features/homepage/containers/latestNewsContainer/index.js
  src/pages/blog.js
  src/templates/blogDetails.js
  src/theme/theme.js
Labels: Blog, QA, Refactoring, size/L

#325 [QA #293] Homepage - Latest news green underline
  src/components/ctaLink/index.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/_mocks.js
  src/features/blog/containers/viewsContainer/_spec.js
  src/features/blog/containers/viewsContainer/index.js
  src/features/homepage/components/latestNews/latestNewsHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/latestNewsHeader/index.js
  src/features/homepage/components/latestNews/latestNewsHeader/styles.js
Labels: Homepage, QA, Refactoring, size/M

#326 Update styling to links
  src/layouts/index.css
Labels: size/XS

#327 [QA] 308 - Homepage - Align everything to the grid
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/footer/index.js
  src/features/blogDetails/components/author/styles.js
  src/features/blogDetails/containers/otherArticles/styles.js
  src/features/help/components/contactForm/index.js
  src/features/homepage/components/announcementCard/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementCard/index.js
  src/features/homepage/components/announcementCard/styles.js
  src/features/homepage/components/announcementHeader/styles.js
  src/features/homepage/components/featuredEvents/index.js
  src/features/homepage/components/featuredEvents/slickSettings.js
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/_spec.js.snap
  src/features/homepage/components/volunteerBoxInfo/index.js
  src/features/homepage/components/volunteerBoxInfo/styles.js
  src/features/homepage/containers/announcementsContainer/index.js
  src/features/homepage/containers/announcementsContainer/slickSettings.js
  src/features/homepage/containers/announcementsContainer/styles.js
  src/features/homepage/containers/donateContainer/index.js
  src/features/homepage/containers/donateContainer/styles.js
  src/features/homepage/containers/latestNewsContainer/index.js
  src/features/homepage/containers/latestNewsContainer/styles.js
  src/pages/events/whats-on.js
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/L

#328 Feature/refactor button
  src/components/button/__snapshots__/_spec.js.snap
  src/components/button/_spec.js
  src/components/button/index.js
  src/components/ctaLink/__snapshots__/_spec.js.snap
  src/components/ctaLink/_spec.js
  src/components/ctaLink/index.js
  src/components/footer/__snapshots__/_spec.js.snap
  src/features/events/components/eventInfoCard.js
  src/features/genericContentPage/__snapshots__/_spec.js.snap
  src/features/genericContentPage/renderMethods.js
  src/features/homepage/components/donateSection/donateButtonsGroup/__snapshots__/_spec.js.snap
  src/features/homepage/components/donateSection/donateButtonsGroup/index.js
  src/features/homepage/components/latestNews/latestNewsHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/_spec.js.snap
  src/features/homepage/components/volunteerBoxInfo/index.js
  src/pages/index.js
  src/pages/support-us/partners.js
  src/utilities/index.js
Labels: Improvement, Refactoring, size/L

#329 [QA #289] Homepage - Latest News border radius
  src/features/homepage/containers/latestNewsContainer/styles.js
Labels: Homepage, QA, Refactoring, size/XS

#330 [QA #226] Generic Content Page - Spacing around titles
  src/components/navigation/nav/__snapshots__/_spec.js.snap
  src/components/navigation/nav/index.js
  src/layouts/index.css
Labels: Generic Content, QA, Refactoring, size/XS

#335 [GitHub] Create a CODEOWNERS file
  .github/.codecov.yml
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
Labels: Improvement, Refactoring

#337 Carousel Section Refactoring
  gatsby-node.js
  src/components/banner/bannerImage/__snapshots__/_spec.js.snap
  src/components/banner/bannerImage/index.js
  src/components/banner/bannerImage/styles.js
  src/components/banner/bannerTitle/styles.js
  src/components/grid/index.js
  src/constants/index.js
  src/features/blog/components/title/__snapshots__/_spec.js.snap
  src/features/blog/components/title/index.js
  src/features/blog/components/title/styles.js
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/_spec.js
  src/features/blog/components/viewsCard/index.js
  src/features/blog/components/viewsCard/styles.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/_mocks.js
  src/features/blog/containers/viewsContainer/_spec.js
  src/features/blog/containers/viewsContainer/index.js
  src/features/blog/containers/viewsContainer/slickSettings.js
  src/features/blog/containers/viewsContainer/styles.js
  src/features/homepage/components/featuredEvents/__snapshots__/_spec.js.snap
  src/features/homepage/components/featuredEvents/_spec.js
  src/features/homepage/components/featuredEvents/index.js
  src/features/homepage/components/featuredEvents/styles.js
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/_spec.js.snap
  src/layouts/index.css
  src/layouts/index.js
  src/pages/blog.js
Labels: Blog, Refactoring, size/XL

#342 Remove parseZone from event functions
  src/features/events/components/eventInfoCard.js
  src/features/events/helpers/index.js
Labels: Improvement, Refactoring, size/M

#343 [QA #287] Homepage - Latest News font
  src/features/homepage/components/latestNews/latestNewsHeader/styles.js
Labels: Homepage, QA, Refactoring, size/XS

#345 [QA #300] Homepage - Featured events title spacing
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/S

#348 [QA #288] Homepage - Volunteer section link
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/_spec.js.snap
  src/features/homepage/components/volunteerBoxInfo/index.js
Labels: Homepage, QA, Refactoring, size/XS

#347 [QA #289] Homepage - Featured events button view all events
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/S

#346 [QA #299] Homepage - Featured events font weight
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/XS

#349 [QA #309] Homepage - Donation background
  src/features/homepage/containers/announcementsContainer/index.js
  src/features/homepage/containers/donateContainer/index.js
  src/features/homepage/containers/donateContainer/styles.js
Labels: Homepage, QA, Refactoring, size/L

#350 [QA #290] Homepage - Latest News white space
  src/features/homepage/components/latestNews/latestNewsHeader/styles.js
Labels: Homepage, QA, Refactoring, size/XS

#351 News Section
  src/components/banner/bannerImage/__snapshots__/_spec.js.snap
  src/components/banner/bannerSubtitle/styles.js
  src/components/footer/__snapshots__/_spec.js.snap
  src/components/grid/index.js
  src/components/icons/star.js
  src/components/newsCardHeader/__snapshots__/_spec.js.snap
  src/components/newsCardHeader/index.js
  src/components/newsCardHeader/styles.js
  src/components/newsCategory/index.js
  src/components/newsCategory/styles.js
  src/components/newsMetrics/index.js
  src/components/newsMetrics/styles.js
  src/features/blog/components/featuredArticle/index.js
  src/features/blog/components/featuredArticle/starIcon.svg
  src/features/blog/components/featuredArticle/styles.js
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/_spec.js
  src/features/blog/components/newsCard/index.js
  src/features/blog/components/newsCard/styles.js
  src/features/blog/components/newsFilter/config.js
  src/features/blog/components/newsFilter/styles.js
  src/features/blog/components/title/styles.js
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/index.js
  src/features/blog/containers/featuredArticleContainer/index.js
  src/features/blog/containers/featuredArticleContainer/styles.js
  src/features/blog/containers/filtersContainer/index.js
  src/features/blog/containers/filtersContainer/styles.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blog/containers/newsContainer/styles.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/index.js
  src/features/blog/containers/viewsContainer/styles.js
  src/features/blogDetails/components/blogHeader/__snapshots__/_spec.js.snap
  src/features/blogDetails/components/blogHeader/index.js
  src/features/blogDetails/containers/otherArticles/__snapshots__/_spec.js.snap
  src/features/blogDetails/containers/pageContent/__snapshots__/_spec.js.snap
  src/features/events/tests/__snapshots__/eventsYouMayLike_spec.js.snap
  src/features/homepage/components/donateSection/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/_spec.js
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/_spec.js.snap
  src/layouts/index.css
  src/pages/blog.js
  src/pages/events/whats-on.js
Labels: Blog, Improvement, Refactoring, size/XXL

#353 [GitHub] Add an open source licence
  LICENSE
Labels: Documentation, Improvement, size/L

#354 [QA #285] Homepage - Drop shadow/corner radius
  src/pages/index.js
Labels: Homepage, QA, Refactoring, size/XS

#356 Feature/blog links
  gatsby-node.js
  src/features/blog/components/featuredArticle/index.js
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/index.js
  src/features/blog/containers/featuredArticleContainer/index.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/blog/containers/newsCards/index.js
  src/features/blogDetails/containers/otherArticles/index.js
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/containers/latestNewsContainer/index.js
  src/pages/blog.js
  src/templates/blogDetails.js
  src/utilities/index.js
Labels: Blog, Refactoring, size/M

#357 [QA #295] Homepage - Featured events aspect ratio
  src/features/events/components/eventListingCard.js
Labels: Homepage, QA, Refactoring, size/S

#359 Restore SEO
  gatsby-config.js
  gatsby-node.js
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/_spec.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/blog/containers/newsCards/_spec.js
  src/features/events/components/eventInfoCard.js
  src/features/events/helpers/index.js
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/_spec.js
  src/layouts/index.js
  src/pages/events/whats-on.js
  src/templates/event.js
  src/theme/assets/images/Pride-in-London-2018-save-the-date1024.jpg
Labels: Refactoring, SEO

#362 Fix date error
  gatsby-node.js
  src/features/blog/containers/newsCards/index.js
  src/features/events/components/eventInfoCard.js
Labels: Refactoring, size/XS

#366 [MVP] GA/GTM #361
  gatsby-config.js
  package.json
  yarn.lock
Labels: Improvement, SEO

#368 [MVP] [QA] Homepage - Announcement section #365
  src/components/button/index.js
  src/components/ctaLink/_spec.js
  src/components/ctaLink/index.js
  src/features/genericContentPage/renderMethods.js
  src/features/homepage/components/announcementCard/__snapshots__/_spec.js.snap
  src/features/homepage/components/announcementCard/index.js
  src/features/homepage/components/announcementCard/styles.js
  src/features/homepage/containers/announcementsContainer/index.js
  src/utilities/index.js
Labels: Homepage, QA, Refactoring, size/L

#360 [QA #292] Homepage - Latest News mobile design
  src/features/blog/components/newsCard/styles.js
  src/features/homepage/components/latestNews/latestNewsHeader/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/latestNewsHeader/index.js
  src/features/homepage/components/latestNews/latestNewsHeader/styles.js
  src/features/homepage/components/latestNews/styles.js
  src/features/homepage/containers/latestNewsContainer/index.js
  src/features/homepage/containers/latestNewsContainer/styles.js
Labels: Homepage, QA, Refactoring, size/L

#369 [MVP] [QA] Partners Section - Add Media/ Digital partners
  src/constants/index.js
  src/pages/support-us/partners.js
Labels: QA, Refactoring, Sponsors, size/S

#336 [GitHub] Add templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, Refactoring, size/XS

#358 [QA #291] Homepage - Featured Latest News clickable
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/index.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/__snapshots__/_spec.js.snap
  src/features/homepage/components/latestNews/index.js
  src/features/homepage/components/latestNews/styles.js
Labels: Homepage, QA, Refactoring, size/XS

#367 [MVP] OG Tags & Twitter cards #170
  src/features/events/components/eventInfoCard.js
  src/layouts/index.js
  src/templates/blogDetails.js
  src/templates/event.js
Labels: Improvement, SEO, size/L

#373 Fix author fields
  src/components/banner/bannerImage/__snapshots__/_spec.js.snap
  src/components/banner/bannerImage/_spec.js
  src/components/banner/bannerImage/index.js
  src/components/banner/bannerSubtitle/styles.js
  src/features/blog/components/viewsCard/_spec.js
  src/features/blog/components/viewsCard/index.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/_mocks.js
  src/features/blogDetails/components/author/_spec.js
  src/features/blogDetails/components/author/index.js
  src/features/genericContentPage/__snapshots__/_spec.js.snap
  src/features/genericContentPage/_mocks.js
  src/features/genericContentPage/components/figure/__snapshots__/_spec.js.snap
  src/features/genericContentPage/components/figure/_spec.js
  src/features/genericContentPage/components/figure/index.js
  src/layouts/index.css
  src/pages/blog.js
  src/pages/index.js
  src/pages/privacy-policy.js
  src/templates/blogDetails.js
Labels: Improvement, Refactoring, size/XXL
