Repository PrideInLondon/pride-london-web, pull requests merged in 2019-03, with the labels that each got.

#51 Feature/frontend updates
  .babelrc
  gatsby-browser.js
  package-lock.json
  package.json
  src/components/bannerSubtitle/_spec.js
  src/components/bannerTitle/_spec.js
  src/components/button/_spec.js
  src/components/checkbox/_spec.js
  src/components/footer/index.js
  src/components/icons/facebook.js
  src/components/icons/instagram.js
  src/components/icons/linkedin.js
  src/components/icons/snapchat.js
  src/components/icons/twitter.js
  src/components/icons/youtube.js
  src/components/image/_spec.js
  src/components/imageBanner/__snapshots__/_spec.js.snap
  src/components/imageBanner/_spec.js
  src/components/imageBanner/index.js
  src/components/input/index.js
  src/components/simpleNav/index.js
  src/features/blog/components/title/_spec.js
  src/features/blog/components/viewsCard/_spec.js
  src/features/blog/containers/newsContainer/_spec.js
  src/features/blog/containers/viewsContainer/_spec.js
  src/features/events/components/eventInfoCard.js
  src/features/events/components/newsletter/index.js
  src/features/events/tests/eventsYouMayLike_spec.js
  src/layouts/index.js
  src/theme/assets/images/icon-facebook.svg
  src/theme/assets/images/icon-instagram.svg
  src/theme/assets/images/icon-linkedin.svg
  src/theme/assets/images/icon-snapchat.svg
  src/theme/assets/images/icon-twitter.svg
  src/theme/assets/images/icon-youtube.svg
  yarn.lock
Labels: enhancement

#65 Adding a CONTRIBUTING.md file
  CONTRIBUTING.md
  README.md
Labels: enhancement

#87 Add Netlify badge on README file
  .env.example
  README.md
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#69 Task/blog page layout
  package.json
  src/components/imageBanner/index.js
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/_spec.js
  src/features/blog/components/newsCard/index.js
  src/features/blog/components/newsCard/styles.js
  src/features/blog/components/newsFilter/__snapshots__/_spec.js.snap
  src/features/blog/components/newsFilter/_spec.js
  src/features/blog/components/newsFilter/index.js
  src/features/blog/components/newsFilter/styles.js
  src/features/blog/components/title/__snapshots__/_spec.js.snap
  src/features/blog/components/title/_spec.js
  src/features/blog/components/title/index.js
  src/features/blog/components/title/styles.js
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/index.js
  src/features/blog/components/viewsCard/styles.js
  src/features/blog/containers/filtersContainer/index.js
  src/features/blog/containers/filtersContainer/styles.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/blog/containers/newsCards/_spec.js
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/_spec.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blog/containers/newsContainer/styles.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/index.js
  src/features/blog/containers/viewsContainer/styles.js
  yarn.lock
Labels: enhancement

#99 Fix/event detail
  gatsby-node.js
  src/components/nav/__snapshots__/_spec.js.snap
  src/components/nav/index.js
  src/features/events/helpers/_spec.js
  src/features/events/helpers/index.js
Labels: enhancement

#122 Fix linting errors in tests
  .eslintrc
  package.json
  src/components/bannerSubtitle/_spec.js
  src/components/checkboxSet/_spec.js
  src/components/nav/_spec.js
  src/components/navItem/_spec.js
  src/components/submenu/_spec.js
  src/features/events/tests/eventsYouMayLike_spec.js
Labels: Hotfix, Refactoring

#134 Sponsors
  src/components/grid/index.js
  src/components/icons/sponsorHeadline.js
  src/components/icons/sponsorStar.js
  src/constants/index.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/sponsors/components/sponsorBadge/__snapshots__/_spec.js.snap
  src/features/sponsors/components/sponsorBadge/_spec.js
  src/features/sponsors/components/sponsorBadge/index.js
  src/features/sponsors/components/sponsorSubsection/__snapshots__/_spec.js.snap
  src/features/sponsors/components/sponsorSubsection/_spec.js
  src/features/sponsors/components/sponsorSubsection/index.js
  src/features/sponsors/helpers/index.js
  src/pages/sponsors.js
  src/theme/assets/images/icon-circle-star.svg
  src/theme/assets/images/icon-headline-star.svg
  src/theme/theme.js
Labels: Improvement, Sponsors

#121 Load articles dynamically on News landing page
  gatsby-node.js
  package.json
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/_spec.js
  src/features/blog/components/newsCard/index.js
  src/features/blog/components/newsCard/styles.js
  src/features/blog/components/newsFilter/__snapshots__/_spec.js.snap
  src/features/blog/components/newsFilter/_spec.js
  src/features/blog/components/newsFilter/index.js
  src/features/blog/components/newsFilter/styles.js
  src/features/blog/components/title/__snapshots__/_spec.js.snap
  src/features/blog/components/title/index.js
  src/features/blog/components/title/styles.js
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/_spec.js
  src/features/blog/components/viewsCard/index.js
  src/features/blog/components/viewsCard/styles.js
  src/features/blog/containers/filtersContainer/index.js
  src/features/blog/containers/filtersContainer/styles.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/blog/containers/newsCards/_spec.js
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/_spec.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/index.js
  src/pages/blog.js
  src/pages/sponsors.js
  src/theme/tinycolor.js
  yarn.lock
Labels: Blog, New Feature

#100 Blog page
  gatsby-node.js
  package-lock.json
  package.json
  src/components/grid/index.js
  src/components/horizontalRule/index.js
  src/components/imageBanner/index.js
  src/features/blog/components/newsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/newsCard/_spec.js
  src/features/blog/components/newsCard/index.js
  src/features/blog/components/newsCard/styles.js
  src/features/blog/components/newsFilter/__snapshots__/_spec.js.snap
  src/features/blog/components/newsFilter/_spec.js
  src/features/blog/components/newsFilter/config.js
  src/features/blog/components/newsFilter/index.js
  src/features/blog/components/newsFilter/styles.js
  src/features/blog/components/title/__snapshots__/_spec.js.snap
  src/features/blog/components/title/_spec.js
  src/features/blog/components/title/index.js
  src/features/blog/components/title/styles.js
  src/features/blog/components/viewsCard/__snapshots__/_spec.js.snap
  src/features/blog/components/viewsCard/_spec.js
  src/features/blog/components/viewsCard/index.js
  src/features/blog/components/viewsCard/styles.js
  src/features/blog/containers/filtersContainer/index.js
  src/features/blog/containers/filtersContainer/styles.js
  src/features/blog/containers/newsCards/__snapshots__/_spec.js.snap
  src/features/blog/containers/newsCards/_spec.js
  src/features/blog/containers/newsCards/index.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blog/containers/newsContainer/styles.js
  src/features/blog/containers/viewsContainer/__snapshots__/_spec.js.snap
  src/features/blog/containers/viewsContainer/index.js
  src/features/blog/containers/viewsContainer/styles.js
  src/pages/blog.js
  src/pages/events.js
  src/theme/tinycolor.js
  yarn.lock
Labels: Blog, New Feature
