Repository PrideInLondon/pride-london-web, pull requests merged in 2020-07, with the labels that each got.

#1551 WEBNEW-167 ✨ Re-added subscribe link to footer
  src/layout/footer/Footer.js
  src/layout/footer/Footer.styles.js
Labels: Subscribe, size/M

#1555 WEBNEW-164 ✨ New footer
  @types/react-intercom/index.d.ts
  package.json
  src/components/button/Button.stories.tsx
  src/components/button/Button.styles.tsx
  src/components/button/Button.types.tsx
  src/components/divider/Divider.stories.tsx
  src/components/divider/Divider.tsx
  src/components/divider/index.ts
  src/components/footer/Footer.stories.tsx
  src/components/footer/Footer.styles.tsx
  src/components/footer/Footer.tsx
  src/components/footer/Footer.types.ts
  src/components/footer/background.jpg
  src/components/footer/index.ts
  src/components/navigate/Navigate.stories.tsx
  src/components/navigate/Navigate.tsx
  src/components/navigate/Navigate.types.ts
  src/components/navigate/index.ts
  src/layout/Footer.tsx
  src/layout/Layout.js
  src/layout/footer/Footer.js
  src/layout/footer/Footer.styles.js
  src/layout/footer/Footer.test.js
  src/layout/footer/index.ts
  src/pages/subscribe.tsx
  src/sponsors/PartnersPage.tsx
  src/sponsors/PartnersPage.types.ts
  src/sponsors/index.ts
  src/sponsors/sponsors.utils.test.ts
  src/sponsors/sponsors.utils.ts
  src/utils/location-utils.test.ts
  src/utils/location-utils.ts
  src/utils/location-utils.types.ts
  yarn.lock
Labels: Navigation, New Component

#1582 WEBNEW-192 💬 Update Donation copy on homepage
  src/homepage/DonateSectionHeader.js
Labels: Homepage, size/XS

#1557 WEBNEW-170 💄 Create Fifty Two CTA Component
  src/components/ctaBox/CTABox.js
  src/components/ctaBox/CTABox.styles.js
  src/components/ctaBox/CTABox.styles.ts
  src/components/ctaBox/CTABox.tsx
  src/components/ctaBox/CTABox.types.ts
  src/components/ctaBox/ctaBox.stories.tsx
  src/components/pageIntro/PageIntro.styles.js
  src/components/pageIntro/PageIntro.styles.ts
  src/components/pageIntro/PageIntro.tsx
  src/components/pageIntro/PageIntro.types.ts
  src/components/pageIntro/pageIntro.stories.tsx
Labels: 52 Gallery, size/L

#1569 WEBNEW-187 💄 Modal Component
  package.json
  src/components/modal/Modal.stories.tsx
  src/components/modal/Modal.styles.tsx
  src/components/modal/Modal.test.tsx
  src/components/modal/Modal.tsx
  src/components/modal/Modal.types.ts
  src/components/modal/navy-background.jpg
  src/hooks/usePickedProps.ts
  yarn.lock
Labels: 52 Gallery

#1599 DSO-9 📦 Update Gatsby dependencies
  package.json
  yarn.lock
Labels: Security

#1585 WEBNEW-180 ✨ Gallery component
  src/components/filterContainer/FilterContainer.stories.tsx
  src/components/filterContainer/FilterContainer.styles.ts
  src/components/filterContainer/FilterContainer.test.js
  src/components/filterContainer/FilterContainer.test.tsx
  src/components/filterContainer/FilterContainer.tsx
  src/components/filterContainer/FilterContainer.types.ts
  src/components/filterContainer/FilterLabel.stories.tsx
  src/components/filterContainer/FilterLabel.styles.js
  src/components/filterContainer/FilterLabel.styles.ts
  src/components/filterContainer/FilterLabel.test.js
  src/components/filterContainer/FilterLabel.test.tsx
  src/components/filterContainer/FilterLabel.tsx
  src/components/filterContainer/FilterLabel.types.ts
  src/components/filteredPagedCardContainer/FilteredPagedCardContainer.test.js
  src/components/gallery/Gallery.stories.tsx
  src/components/gallery/Gallery.test.tsx
  src/components/gallery/Gallery.tsx
  src/components/gallery/Gallery.types.ts
  src/components/gallery/GalleryContainer.styles.ts
  src/components/gallery/GalleryContainer.tsx
  src/components/gallery/GalleryContainer.types.ts
  src/components/gallery/index.ts
  src/components/masonry/Masonry.stories.tsx
  src/components/masonry/Masonry.styles.ts
  src/components/masonry/Masonry.test.ts
  src/components/masonry/Masonry.tsx
  src/components/masonry/Masonry.types.ts
  src/components/masonry/index.ts
  src/hooks/useEventListener.ts
  src/theme/breakpoints.ts
  src/utils/color-utils.ts
Labels: 52 Gallery, New Component

#1610 WEBNEW-191 Generate artwork detail pages with Contentful entries
  gatsby-node.esm.js
  src/fifty-two/FiftyTwoDetailPage.tsx
Labels: 52 Gallery, size/M

#1614 DSO-42 📦 Update dependencies
  package.json
  yarn.lock
Labels: Dependencies, Security, size/L

#1618 WEBNEW-177 ✨ Implement age verification modal
  package.json
  src/components/modal/Modal.tsx
  src/fifty-two/FiftyTwoPage.tsx
  yarn.lock
Labels: 52 Gallery, New Feature, size/M

#1619 WEBNEW-177 ✨ Add modal to entry pages
  src/components/pageSwitcher/PageSwitcher.styles.tsx
  src/fifty-two/AgeVerification.tsx
  src/fifty-two/FiftyTwoPage.tsx
  src/fifty-two/entry/FiftyTwoEntryPage.tsx
Labels: size/M

#1620 WEBNEW-182 ✨ Fifty-Two entry page
  gatsby-node.esm.js
  package.json
  src/components/categoryFilter/CategoryFilter.test.ts
  src/components/modal/Modal.tsx
  src/components/pageSwitcher/PageSwitcher.stories.tsx
  src/components/pageSwitcher/PageSwitcher.styles.tsx
  src/components/pageSwitcher/PageSwitcher.tsx
  src/components/tag/Tag.styles.ts
  src/components/tag/Tag.types.ts
  src/fifty-two/AgeVerification.tsx
  src/fifty-two/FiftyTwoDetailPage.tsx
  src/fifty-two/FiftyTwoPage.tsx
  src/fifty-two/entry/AboutTheArtist.styles.ts
  src/fifty-two/entry/AboutTheArtist.tsx
  src/fifty-two/entry/AboutTheArtist.types.ts
  src/fifty-two/entry/AboutTheArtwork.tsx
  src/fifty-two/entry/AboutTheArtwork.types.ts
  src/fifty-two/entry/FiftyTwoEntryPage.styles.ts
  src/fifty-two/entry/FiftyTwoEntryPage.tsx
  src/fifty-two/entry/FiftyTwoEntryPage.types.ts
  src/pages/fifty-two-2.js
  yarn.lock
Labels: 52 Gallery

#1586 WEBNEW-171💄 Add ShareBar to article pages
  src/blog/article/ArticlePage.js
  src/blog/article/BlogFooter.js
  src/blog/article/BlogFooter.tsx
  src/blog/article/BlogHeader.js
  src/blog/article/BlogHeader.styles.js
  src/blog/article/BlogHeader.tsx
  src/blog/article/PageContent.js
  src/blog/article/PageContent.styles.js
  src/blog/article/PageContent.styles.tsx
  src/blog/article/PageContent.tsx
  src/blog/article/PageContent.types.ts
  src/blog/article/blogContent/BlogContent.js
  src/blog/article/blogContent/BlogContent.tsx
  src/components/shareBar/ShareBar.styles.tsx
  src/components/shareBar/ShareBar.tsx
Labels: Blog Details, size/L
