Repository PrideInLondon/pride-london-web, pull requests merged in 2020-09, with the labels that each got.

#1678 DSO-47 📝 Update privacy page
  src/privacy/PrivacyPage.js
Labels: Security, size/S

#1687 WEBNEW-203 📌 Explicitly pin gatsby-link to 2.4.3
  package.json
  yarn.lock
Labels: Bug, Generic Content, size/S

#1686 WEBREF-116 🐛 Storybook failing to build
  .storybook/config.js
  src/layout/GlobalStyle.js
  src/layout/Layout.js
  src/layout/Layout.styles.js
  src/layout/index.ts
Labels: Bug, size/XL

#1692 WEBNEW-155 ✨ Ripped section component
  src/components/rippedSection/Rip.tsx
  src/components/rippedSection/Rip.types.ts
  src/components/rippedSection/RippedSection.stories.tsx
  src/components/rippedSection/RippedSection.styles.tsx
  src/components/rippedSection/RippedSection.tsx
  src/components/rippedSection/RippedSection.types.ts
  src/components/rippedSection/index.ts
  src/components/rippedSection/ripVariants/RipVariant.styles.ts
  src/components/rippedSection/ripVariants/RipVariant.types.ts
  src/components/rippedSection/ripVariants/RipVariant1.tsx
  src/components/rippedSection/ripVariants/RipVariant2.tsx
  src/components/rippedSection/ripVariants/RipVariant3.tsx
  src/components/rippedSection/ripVariants/RipVariant4.tsx
  src/components/rippedSection/ripVariants/RipVariant5.tsx
  src/components/rippedSection/ripVariants/index.ts
  src/components/tornBackground/TornBackground.stories.tsx
  src/components/tornBackground/TornBackground.styles.tsx
  src/components/tornBackground/TornBackground.tsx
  src/components/tornBackground/tears/Rip1.tsx
  src/components/tornBackground/tears/Rip2.tsx
  src/components/tornBackground/tears/Rip3.tsx
  src/components/tornBackground/tears/Rip4.tsx
  src/components/tornBackground/tears/Rip5.tsx
  src/components/tornBackground/tears/Tears.tsx
Labels: New Component, Redesign, size/XL

#1693 WEBREF-80 🔥 Remove Form components
  src/components/checkbox/Checkbox.js
  src/components/checkbox/Checkbox.test.js
  src/components/checkbox/index.ts
  src/components/icons/checkIcon.svg
  src/components/input/Input.styles.ts
  src/components/input/Input.test.js
  src/components/input/Input.tsx
  src/components/input/Input.types.ts
  src/components/input/index.ts
Labels: Refactoring, size/L

#1704 WEBNEW-141 🔍 update JSON LD for event seo
  src/events/event/EventPage.js
Labels: SEO, size/M

#1705 WEBREF-120 ⬆️ Upgraded Storybook to 5.3.x
  .storybook/addons.js
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: Dependencies, size/XL
