Repository PrideInLondon/pride-london-web, pull requests merged in 2020-01, with the labels that each got.

#1232 EVE-11: Refactor the Button component in TypeScript
  .eslintrc.js
  .prettierrc
  .storybook/webpack.config.js
  gatsby-browser.js
  gatsby-node.js
  gatsby-ssr.js
  package.json
  src/components/appContext/index.js
  src/components/button/Button.stories.tsx
  src/components/button/Button.styles.tsx
  src/components/button/Button.test.js
  src/components/button/Button.tsx
  src/components/button/Button.types.tsx
  src/components/button/__snapshots__/Button.test.js.snap
  src/components/button/__snapshots__/index.test.js.snap
  src/components/button/index.js
  src/components/ctaBox/__snapshots__/index.test.js.snap
  src/components/ctaBox/index.js
  src/components/ctaBox/styles.js
  src/components/ctaLink/CTALink.stories.tsx
  src/components/filterButton/styles.js
  src/components/filteredPagedCardContainer/__snapshots__/index.test.js.snap
  src/components/icons/index.js
  src/components/navigation/nav/__snapshots__/index.test.js.snap
  src/components/navigation/nav/index.js
  src/components/navigation/nav/styles.js
  src/components/pagedCardContainer/__snapshots__/index.test.js.snap
  src/components/pagedCardContainer/showMoreButton/__snapshots__/index.test.js.snap
  src/components/pagedCardContainer/showMoreButton/index.js
  src/features/blog/containers/newsContainer/index.js
  src/features/blogDetails/containers/pageContent/index.test.js
  src/features/events/components/eventInfoCard.js
  src/features/events/components/eventShareSection.js
  src/features/events/components/eventsFilters.js
  src/features/events/components/newsletter/index.js
  src/features/events/filters/eventDropdownFilter.js
  src/features/genericContentPage/__snapshots__/index.test.js.snap
  src/features/genericContentPage/renderMethods.js
  src/features/help/components/contactForm/index.js
  src/features/help/components/dropDown.js
  src/features/homepage/components/donateSection/donateButtonsGroup/__snapshots__/index.test.js.snap
  src/features/homepage/components/donateSection/donateButtonsGroup/index.js
  src/features/homepage/components/featuredEvents/featuredEventsQuery.js
  src/features/homepage/components/volunteerBoxInfo/__snapshots__/index.test.js.snap
  src/features/homepage/components/volunteerBoxInfo/index.js
  src/features/paradeGroups/containers/paradeGroupsContainer/index.test.js
  src/hooks/useSpaceLayoutProps.ts
  src/layouts/fonts.css
  src/pages/events.js
  src/pages/parade/map/__snapshots__/index.test.js.snap
  src/pages/parade/map/index.js
  src/theme/fonts.ts
  src/theme/theme.ts
  src/utilities/index.ts
  storybook/addons.js
  storybook/config.js
  storybook/tsconfig.json
  storybook/webpack.config.js
  yarn.lock
Labels: Refactoring

#1209 EVE-9: removal of flipmove
  package.json
  src/components/filteredPagedCardContainer/__snapshots__/index.test.js.snap
  src/components/footer/__snapshots__/index.test.js.snap
  src/components/grid/Grid.styles.tsx
  src/components/grid/__snapshots__/index.test.js.snap
  src/components/grid/index.js
  src/components/grid/index.test.js
  src/components/pagedCardContainer/__snapshots__/index.test.js.snap
  src/features/events/components/groupedEventsCard.js
  src/features/events/index.js
  src/features/events/tests/__mocks__/index.js
  src/features/events/tests/__snapshots__/groupedEventsCard.test.js.snap
  src/features/events/tests/groupedEventsCard.test.js
  src/pages/events.js
  yarn.lock
Labels: Event, Refactoring

#1230 WER-30: ♻️ Refactor NewsletterForm into functional component with hooks
  src/features/events/components/newsletter/index.js
Labels: Refactoring, size/M

#1264 WEBNEW-45: ♻️ Update menu for Take Part Generic Page
  src/components/navigation/nav/__snapshots__/index.test.js.snap
  src/components/navigation/nav/index.js
Labels: Homepage, Refactoring, size/S

#1265 WEBREF-45: ♻️Update README to remove Codacy badge
  README.md
Labels: Documentation, Refactoring, size/XS

#1268 WEBNEW-41: Parade applications component on the homepage
  src/components/horizontalRule/index.js
  src/features/homepage/components/paradeApplications/index.js
  src/pages/index.js
  src/theme/assets/images/parade-applications-bg.jpg
Labels: Event

#1191 SEO-6: Patch for update tiles and description in listed sub tickets
  src/components/helmetComponent/__snapshots__/index.test.js.snap
  src/components/helmetComponent/index.js
  src/components/helmetComponent/index.test.js
  src/layouts/index.js
  src/pages/events.js
  src/pages/explore-london.js
  src/templates/genericContentPage.js
Labels: SEO, size/M

#1274 WEBNEW-54: events missing from site
  src/features/events/helpers/index.js
Labels: Bug, size/M

#1267 WEBNEW-30 ♻️ Refactor EventCard Component
  .eslintignore
  .eslintrc.js
  .storybook/addons.js
  .storybook/config.js
  .storybook/tsconfig.json
  .storybook/webpack.config.js
  @types/index.d.ts
  package.json
  src/components/button/Button.stories.tsx
  src/components/card/Card.stories.tsx
  src/components/card/Card.tsx
  src/components/card/Card.types.ts
  src/components/card/index.tsx
  src/components/card/umbrella.jpg
  src/components/ctaLink/CTALink.stories.tsx
  src/features/events/components/eventListingCard.js
  src/features/events/components/eventsPageBanner/EventsPageBanner.tsx
  src/features/events/components/eventsYouMayLike.js
  src/features/events/components/groupedEventsCard.js
  src/features/events/filters/eventDateFilter.js
  src/features/events/helpers/eventCard.test.js
  src/features/events/helpers/eventCard.ts
  src/features/events/tests/__snapshots__/eventsYouMayLike.test.js.snap
  src/features/events/tests/__snapshots__/groupedEventsCard.test.js.snap
  src/features/homepage/components/featuredEvents/__snapshots__/index.test.js.snap
  src/layouts/index.js
  src/layouts/index.styles.js
  src/pages/events.js
  src/theme/assets/fonts/roboto/roboto-v20-latin-300.eot
  src/theme/assets/fonts/roboto/roboto-v20-latin-300.svg
  src/theme/assets/fonts/roboto/roboto-v20-latin-300.ttf
  src/theme/assets/fonts/roboto/roboto-v20-latin-300.woff
  src/theme/assets/fonts/roboto/roboto-v20-latin-300.woff2
  src/theme/assets/images/calendar-icon.js
  src/theme/assets/images/icon-calendar.svg
  src/theme/colors.ts
Labels: Event Details, Refactoring

#1277 WEBNEW-57 💄 Turned off center mode for announcement carousel
  src/features/homepage/containers/announcementsContainer/slickSettings.js
Labels: Bug, size/XS

#1278 WEBREF-16 ♻️ Add hooks to input component
  src/components/input/Input.styles.ts
  src/components/input/Input.test.js
  src/components/input/Input.tsx
  src/components/input/Input.types.ts
  src/components/input/__snapshots__/Input.test.js.snap
  src/components/input/index.js
Labels: Refactoring, size/L

#1286 WEBREF-50 🔧 move husky and lintstaged configs
  .huskyrc
  .lintstagedrc
  package.json
Labels: Refactoring, size/S

#1284 WEBREF-51 🔥 remove console logs appearing in test run
  config/jest.setup.js
  src/features/events/tests/groupedEventsCard.test.js
Labels: Refactoring, size/XS

#1285 WEBREF-48 ⬆️ upgraded to node 12
  .circleci/config.yml
  .nvmrc
Labels: Refactoring, size/XS

#1287 WEBREF 25 implement react testing library
  @types/index.d.ts
  @types/styled-components/index.d.ts
  __mocks__/gatsby.ts
  config/jest.setup.js
  config/jest.setup.ts
  jest.config.js
  package.json
  src/components/card/Card.test.tsx
  src/utilities/testing.tsx
  tsconfig.json
  yarn.lock
Labels: Refactoring, size/L

#1279 WEBNEW-37 🔍 Privacy and Line Up redirects
  how-to-guide.md
  static/_redirects
Labels: SEO, size/S

#1297 WEBREF-49 📦 Resolved react-side-effect dependency
  package.json
  yarn.lock
Labels: Refactoring, size/S

#1299 WEBREF-57 🔥 Remove coverage report from local test run
  .circleci/config.yml
  jest.config.js
  package.json
Labels: Refactoring, size/S

#1302 WEBREF-58 🔧 Added a recommended list of vscode extensions
  .gitignore
  .vscode/extensions.json
Labels: Refactoring, size/XS
