Repository PrideInLondon/pride-london-web, pull requests merged in 2020-08, with the labels that each got.

#1629 WEBNEW-182 Entry page fixes
  src/components/icon/Icon.tsx
  src/components/icon/Icon.utils.test.tsx
  src/components/icon/Icon.utils.ts
  src/components/modal/Modal.styles.tsx
  src/components/pageSwitcher/PageSwitcher.tsx
  src/fifty-two/AgeVerification.tsx
Labels: 52 Gallery, size/M

#1617 WEBNEW-179 ✨ Fifty-Two hub
  gatsby-node.esm.js
  package.json
  src/components/categoryFilter/CategoryFilter.stories.tsx
  src/components/categoryFilter/CategoryFilter.styles.ts
  src/components/categoryFilter/CategoryFilter.test.ts
  src/components/categoryFilter/CategoryFilter.tsx
  src/components/categoryFilter/CategoryFilter.types.ts
  src/components/categoryFilter/index.ts
  src/components/ctaBox/CTABox.stories.tsx
  src/components/ctaBox/CTABox.tsx
  src/components/ctaBox/index.ts
  src/components/filteredPagedCardContainer/index.ts
  src/components/gallery/Gallery.stories.tsx
  src/components/gallery/Gallery.test.tsx
  src/components/gallery/Gallery.tsx
  src/components/gallery/GalleryContainer.styles.ts
  src/components/gallery/GalleryContainer.tsx
  src/components/gallery/GalleryContainer.types.ts
  src/components/galleryCard/GalleryCard.stories.tsx
  src/components/galleryCard/GalleryCard.styles.ts
  src/components/galleryCard/GalleryCard.tsx
  src/components/galleryCard/GalleryCard.types.ts
  src/components/helmet/Helmet.tsx
  src/components/helmet/index.ts
  src/components/icon/Icon.tsx
  src/components/icon/Icon.utils.test.tsx
  src/components/icon/Icon.utils.ts
  src/components/masonry/Masonry.styles.ts
  src/components/masonry/Masonry.tsx
  src/components/masonry/Masonry.types.ts
  src/components/modal/Modal.styles.tsx
  src/components/modal/Modal.tsx
  src/components/pageIntro/PageIntro.tsx
  src/components/pageSwitcher/PageSwitcher.stories.tsx
  src/components/pageSwitcher/PageSwitcher.styles.tsx
  src/components/pageSwitcher/PageSwitcher.tsx
  src/components/tag/Tag.styles.ts
  src/components/tag/Tag.types.ts
  src/fifty-two/AgeVerification.tsx
  src/fifty-two/FiftyTwoPage.styles.ts
  src/fifty-two/FiftyTwoPage.tsx
  src/fifty-two/FiftyTwoPage.types.ts
  src/fifty-two/entry/AboutTheArtist.styles.ts
  src/fifty-two/entry/AboutTheArtist.tsx
  src/fifty-two/entry/AboutTheArtist.types.ts
  src/fifty-two/entry/AboutTheArtwork.tsx
  src/fifty-two/entry/AboutTheArtwork.types.ts
  src/fifty-two/entry/FiftyTwoEntryPage.styles.ts
  src/fifty-two/entry/FiftyTwoEntryPage.tsx
  src/fifty-two/entry/FiftyTwoEntryPage.types.ts
  src/fifty-two/helpers.ts
  src/fifty-two/meta.jpg
  src/fifty-two/renderMethods.tsx
  src/hooks/useEventListener.ts
  src/layout/navigation/Navigation.tsx
  src/pages/fifty-two.js
  src/utils/iteration-utils.ts
  src/utils/location-utils.test.ts
  src/utils/location-utils.ts
  yarn.lock
Labels: 52 Gallery, size/XXL

#1639 WEBNEW-196 💄 Updated body text links to match new design
  src/fifty-two/renderMethods.tsx
Labels: 52 Gallery, size/S

#1637 WEBNEW-197 💄 Bumped padding on Fifty-Two entry page
  src/fifty-two/entry/FiftyTwoEntryPage.tsx
Labels: 52 Gallery, size/XS

#1638 WEBNEW-198 🐛 Exclude fallback colours from tag font
  src/components/tag/Tag.styles.ts
Labels: 52 Gallery, size/XS

#1628 WEBNEW-173 💄 Different padding for article page
  src/blog/article/BlogHeader.styles.js
  src/blog/article/BlogHeader.tsx
  src/blog/article/PageContent.tsx
  src/blog/article/blogContent/BlogContent.styles.js
  src/components/wrapper/Wrapper.tsx
Labels: Blog Details, size/M

#1640 WEBNEW-60 🐛 Fixed news-and-views link
  src/blog/article/OtherArticlesHeader.js
  src/blog/article/OtherArticlesHeader.styles.js
Labels: Blog, Bug, size/S

#1647 WEBNEW-199 💬 Update menu bar for Pride in the City
  src/layout/navigation/Navigation.tsx
Labels: Navigation, size/XS

#1656 DSO-45 📝 Fix whitespace for CodeQL status badge
  README.md
Labels: Security, size/XS

#1664 DSO-46 :fire: Remove gatsby-plugin-offline
  gatsby-config.js
  package.json
  yarn.lock
Labels: Environment, size/L
