Repository PrideInLondon/pride-london-web, pull requests merged in 2020-11, with the labels that each got.

#1757 WEBREF-78 ✅ Blog - Migrate to React Testing Library
  src/blog/NewsContainer.test.tsx
  src/blog/ViewsContainer.test.js
  src/blog/ViewsContainer.test.tsx
Labels: Refactoring, size/M

#1772 WEBREF-85 ✅ Grid - Migrate to React Testing Library
  src/components/grid/Grid.test.tsx
Labels: Refactoring, size/S

#1423 WEBNEW-72 🚸 Replace custom cookie with metomic
  @types/global.d.ts
  package.json
  src/components/banner/Banner.js
  src/components/banner/Banner.styles.js
  src/components/banner/Banner.test.js
  src/components/footer/Footer.styles.tsx
  src/components/footer/Footer.tsx
  src/genericContentPage/Video.js
  src/genericContentPage/Video.styles.js
  src/homepage/HomePage.js
  src/homepage/bannerBackground.jpg
  src/homepage/videoPoster.jpg
  src/layout/Layout.js
  yarn.lock
Labels: New Component, size/L

#1797 WEBREF-123 ⬆️ gatsby-link upgrade
  package.json
  src/components/button/Button.tsx
  yarn.lock
Labels: Dependencies, Refactoring, size/M

#1796 WEBREF-128 🔥 Removed deprecated cookie component
  src/cookieNotice.js
  src/cookieNotice.test.js
Labels: Refactoring, size/L
