Repository PrideInLondon/pride-london-web, pull requests merged in 2020-12, with the labels that each got.

#1795 WEBNEW-222 📈 Added GTM to prod site via plugin
  gatsby-config.js
  package.json
  yarn.lock
Labels: Analytics, Environment, size/S

#1784 WEBNEW-207 💄 Ripped section height bug
  src/components/rippedSection/ripVariants/RipVariant1.tsx
  src/components/rippedSection/ripVariants/RipVariant2.tsx
  src/components/rippedSection/ripVariants/RipVariant3.tsx
  src/components/rippedSection/ripVariants/RipVariant4.tsx
  src/components/rippedSection/ripVariants/RipVariant5.tsx
Labels: Bug, Design, size/M

#1804 WEBREF-127 ✨ Fuzzy search for a gitmoji for commit message
  package.json
  src/scripts/prepare-commit-msg/prepare-commit-msg.js
  yarn.lock
Labels: Environment, size/M

#1805 WEBNEW-211 ✨ TalentProfile component
  src/components/renderMethods.tsx
  src/components/talentProfile/TalentProfile.stories.tsx
  src/components/talentProfile/TalentProfile.styles.ts
  src/components/talentProfile/TalentProfile.test.tsx
  src/components/talentProfile/TalentProfile.tsx
  src/components/talentProfile/TalentProfile.types.ts
  src/components/talentProfile/__mocks__/index.ts
  src/components/talentProfile/index.ts
  src/fifty-two/FiftyTwoPage.tsx
  src/fifty-two/entry/AboutTheArtist.tsx
  src/fifty-two/entry/AboutTheArtist.types.ts
  src/fifty-two/entry/AboutTheArtwork.tsx
  src/fifty-two/entry/FiftyTwoEntryPage.tsx
Labels: New Component, size/L

#1822 WEBNEW-224 👽 Added second case for video render
  src/genericContentPage/renderMethods.js
Labels: Generic Content, size/XS

#1824 Revert "WEBNEW-224 👽 Added second case for video render"
  src/genericContentPage/renderMethods.js
Labels: Generic Content, size/XS

#1827 WEBNEW-225 🔧 Update menu and redirects for PGT
  src/layout/navigation/Navigation.tsx
  static/_redirects
Labels: Navigation, size/XS
