Repository PrideInLondon/pride-london-web, pull requests merged in 2020-05, with the labels that each got.

#1441 WEBNEW 111 - Event detail dates
  src/events/event/EventInfoCard.js
  src/events/event/EventPage.js
  src/events/event/EventPage.styles.js
  src/events/event/EventUpcomingDates.tsx
  src/events/helpers.test.js
  src/events/helpers.ts
  src/hooks/useMedia.ts
Labels: Event Details, size/L

#1439 WEBREF-104 ⚡️ Added exception to git hook for when rebasing
  src/scripts/prepare-commit-msg/git-utils.js
  src/scripts/prepare-commit-msg/prepare-commit-msg.js
Labels: Environment, size/S

#1455 WEBNEW-120 📦 Update Gatsby Dependencies
  package.json
  yarn.lock
Labels: Security

#1456 WEBNEW-103 👽 Cleanup remaining usages of old date schema
  gatsby-node.esm.js
  src/events/EventsPage.js
  src/events/GroupedEventsCards.js
  src/events/GroupedEventsCards.test.js
  src/events/__mocks__/index.js
  src/events/event/EventInfoCard.js
  src/events/event/EventInfoCard.test.js
  src/events/event/EventPage.js
  src/events/helpers.test.js
  src/events/helpers.ts
  src/layout/Layout.js
Labels: Event, size/L

#1460 WEBNEW-118 ✨ Live now/on demand events
  src/components/icons/AccessibilityIcon.tsx
  src/components/icons/CalendarIcon.tsx
  src/components/icons/GenderIcon.tsx
  src/components/icons/Icon.types.ts
  src/components/icons/LiveIcon.tsx
  src/components/icons/MapPinIcon.tsx
  src/components/icons/OnDemandIcon.tsx
  src/components/icons/accessibilityIcon.js
  src/components/icons/calendarIcon.js
  src/components/icons/dateIcon.js
  src/components/icons/index.js
  src/events/event/EventInfoCard.js
  src/events/event/EventInfoCard.styles.ts
  src/events/event/EventInfoCard.test.tsx
  src/events/event/EventInfoCard.tsx
  src/events/event/EventInfoCard.types.ts
  src/events/eventListingCard/EventListingCard.styles.ts
  src/events/eventListingCard/EventListingCard.test.ts
  src/events/eventListingCard/EventListingCard.tsx
  src/events/eventListingCard/EventListingCard.types.ts
  src/events/eventListingCard/EventListingCard.utils.ts
  src/events/helpers.test.js
  src/events/helpers.ts
  src/exploreLondon/CommunityPartnerCard.js
  src/layout/Layout.js
Labels: Event, size/XXL

#1462 WEBREF-105 🚨 Ignore valid unused variables to quieten LGTM
  src/components/ctaLink/CTALink.tsx
  src/layout/navigation/SubMenu.tsx
Labels: Improvement, size/XS

#1461 WEBREF-73 ✨ New Icon component
  how-to-guide.md
  src/components/icon/Icon.stories.tsx
  src/components/icon/Icon.tsx
  src/components/icon/Icon.types.ts
  src/components/icon/Icon.utils.ts
  src/components/icon/icons/Calendar.tsx
  src/components/icon/icons/Laptop.tsx
  src/components/icon/icons/Live.tsx
  src/components/icon/icons/OnDemand.tsx
  src/components/icon/index.ts
  src/components/icons/CalendarIcon.tsx
  src/components/icons/LiveIcon.tsx
  src/components/icons/OnDemandIcon.tsx
  src/components/icons/index.js
  src/events/event/EventInfoCard.tsx
  src/events/eventListingCard/EventListingCard.tsx
Labels: Refactoring, size/L

#1464 WEBNEW-138 📝 Update Parage Groups page copy
  src/parade/ParadeGroupsPage.js
Labels: Parade Groups, Refactoring, size/XS

#1465 WEBNEW-139 📝 Update nav bar for parade 2021
  src/layout/navigation/Navigation.tsx
Labels: Navigation, size/XS

#1463 WEBNEW-134/grid-component
  src/campaigns/youMeUsWe/GridList/GridList.styles.ts
  src/campaigns/youMeUsWe/GridList/GridList.test.tsx
  src/campaigns/youMeUsWe/GridList/GridList.tsx
  src/campaigns/youMeUsWe/GridList/index.ts
  src/campaigns/youMeUsWe/YouMeUsWe.stories.tsx
  src/components/ctaLink/CTALink.tsx
  src/components/ctaLink/CTALink.types.ts
  src/fonts/cactus/Cactus-Bold.otf
  src/fonts/cactus/Cactus-BoldItalic.otf
  src/homepage/LatestNewsContainer.js
  src/layout/Layout.styles.js
  src/theme/breakpoints.ts
  src/theme/fonts.ts
  src/theme/space.ts
  src/theme/theme.ts
Labels: Campaign, New Component

#1474 WEBREF-54 ✨ Add typo components
  src/components/typography/Typography.stories.tsx
  src/components/typography/Typography.tsx
  src/theme/breakpoints.ts
  src/theme/fonts.ts
  src/theme/theme.ts
Labels: New Component, Refactoring, size/L

#1476 WEBNEW-137 ✨ Create CTA box component
  src/components/box/Box.stories.tsx
  src/components/box/Box.tsx
  src/components/typography/Typography.tsx
Labels: Campaign, New Component, size/M

#1475 WEBNEW-131 ✨ Share bar component
  how-to-guide.md
  src/components/icon/Icon.test.tsx
  src/components/icon/Icon.utils.ts
  src/components/icon/icons/Calendar.tsx
  src/components/icon/icons/Email.tsx
  src/components/icon/icons/Facebook.tsx
  src/components/icon/icons/Laptop.tsx
  src/components/icon/icons/LinkedIn.tsx
  src/components/icon/icons/Live.tsx
  src/components/icon/icons/Messenger.tsx
  src/components/icon/icons/OnDemand.tsx
  src/components/icon/icons/Twitter.tsx
  src/components/icon/icons/index.ts
  src/components/shareBar/ShareBar.stories.tsx
  src/components/shareBar/ShareBar.styles.ts
  src/components/shareBar/ShareBar.test.tsx
  src/components/shareBar/ShareBar.tsx
  src/components/shareBar/ShareBar.types.ts
  src/components/shareBar/ShareBar.utils.test.ts
  src/components/shareBar/ShareBar.utils.ts
  src/components/shareBar/index.ts
  src/utils/share-utils.test.ts
  src/utils/share-utils.ts
Labels: Campaign, New Component, size/L

#1479 WEBNEW-140 💬 Update thumbnail copy for parade 2020
  LICENSE
  gatsby-config.js
  src/components/helmet/Helmet.tsx
  src/components/shareBar/ShareBar.stories.tsx
Labels: Campaign, Refactoring, size/S

#1477 WEBNEW-132 ✨ Create play button component
  src/components/icon/Icon.utils.ts
  src/components/icon/icons/Play.tsx
  src/components/icon/icons/index.ts
  src/components/playButton/PlayButton.stories.tsx
  src/components/playButton/PlayButton.styles.tsx
  src/components/playButton/PlayButton.tsx
  src/components/playButton/index.ts
Labels: Campaign, New Component, size/M

#1494 DSO-28 📝 Add GuardRails badge on README file
  README.md
Labels: Security, size/XS

#1478 WEBNEW-124 ✨ Background image component
  src/components/tornBackground/TornBackground.stories.tsx
  src/components/tornBackground/TornBackground.styles.tsx
  src/components/tornBackground/TornBackground.tsx
  src/components/tornBackground/tears/Rip1.tsx
  src/components/tornBackground/tears/Rip2.tsx
  src/components/tornBackground/tears/Rip3.tsx
  src/components/tornBackground/tears/Rip4.tsx
  src/components/tornBackground/tears/Rip5.tsx
  src/components/tornBackground/tears/Tears.tsx
Labels: Campaign, New Component, size/L

#1495 DSO-2 🔧 Update Dependabot preferences
  .dependabot/config.yml
Labels: Security, size/XS

#1497 WEBNEW-145 💬 Update copy for 2020 sponsors
  src/layout/footer/Footer.js
  src/sponsors/PartnersPage.js
Labels: Sponsors, size/XS
