Repository PrideInLondon/pride-london-web, pull requests merged in 2020-02, with the labels that each got.

#1301 WEBREF-31 📦 Extreme dependency clean out
  .lintstagedrc
  package.json
  yarn.lock
Labels: Refactoring

#1312 WEBNEW-56 🐛 Extra char in Google Maps link address from community partner card component
  src/features/exploreLondon/components/communityPartnerCard/index.js
Labels: Bug, size/XS

#1283 WEBREF-15 ♻️ Add hooks to checkboxset component
  src/components/appContext/index.js
  src/components/checkboxSet/CheckboxSet.styles.ts
  src/components/checkboxSet/CheckboxSet.test.js
  src/components/checkboxSet/CheckboxSet.tsx
  src/components/checkboxSet/CheckboxSet.types.tsx
  src/components/checkboxSet/__snapshots__/index.test.js.snap
  src/components/checkboxSet/index.js
Labels: Refactoring, size/L

#1304 WEBNEW-55 🐛 Resolve wrapped text styling in nav underline
  src/components/navigation/submenu/styles.js
Labels: Bug, size/S

#1288 WEBREF-47 ♻️ Remove unnecessary global mocks and imports from unit tests
  config/jest.setup.js
  config/jest.setup.ts
  src/components/banner/bannerDate/index.test.js
  src/components/banner/bannerImage/index.test.js
  src/components/banner/bannerSubtitle/index.test.js
  src/components/banner/bannerTitle/index.test.js
  src/components/button/Button.test.js
  src/components/checkbox/index.test.js
  src/components/checkboxSet/CheckboxSet.test.js
  src/components/cookieNotice/index.test.js
  src/components/ctaLink/CTALink.test.js
  src/components/filterButton/index.test.js
  src/components/filterContainer/filterLabel/__snapshots__/index.test.js.snap
  src/components/filteredPagedCardContainer/__snapshots__/index.test.js.snap
  src/components/footer/index.test.js
  src/components/navigation/nav/index.test.js
  src/components/navigation/navItem/index.test.js
  src/components/navigation/submenu/index.test.js
  src/components/pagedCardContainer/__snapshots__/index.test.js.snap
  src/components/sponsors/components/sponsorBadge/__snapshots__/index.test.js.snap
  src/features/blog/components/viewsCard/index.test.js
  src/features/blog/containers/viewsContainer/index.test.js
  src/features/events/tests/groupedEventsCard.test.js
  src/features/genericContentPage/components/figure/index.test.js
  src/features/genericContentPage/components/video/index.test.js
  src/features/genericContentPage/index.test.js
  src/features/homepage/components/featuredEvents/index.test.js
  src/features/paradeGroups/components/letterLink/index.test.js
  src/features/paradeGroups/containers/paradeGroupsContainer/index.test.js
Labels: Refactoring, size/L

#1328 WEBREF-61 🐛 Strip invalid Win32 chars from event URL
  src/features/events/helpers/index.js
  src/features/events/helpers/index.test.js
  static/_redirects
Labels: Bug, size/XS

#1327 WEBREF-53 ✨ Automated commit message hook
  .gitignore
  .huskyrc
  package.json
  src/scripts/prepare-commit-msg/git-utils.js
  src/scripts/prepare-commit-msg/gitmoji-utils.js
  src/scripts/prepare-commit-msg/index.js
  src/scripts/prepare-commit-msg/prepare-commit-msg.js
  src/scripts/run-script.js
  yarn.lock
Labels: New Feature, size/L

#1330 WEBNEW-64 ♻️Add Pride's Got Talent on menu
  src/components/navigation/nav/__snapshots__/index.test.js.snap
  src/components/navigation/nav/index.js
Labels: Homepage, size/XS

#1333 WEBREF-62 ✏️ Add Code of Conduct
  .github/CODE_OF_CONDUCT.md
Labels: Documentation, size/M

#1332 WEBREF-60 🔒 Secure node version
  .circleci/config.yml
  .nvmrc
  src/components/footer/__snapshots__/index.test.js.snap
  src/features/events/components/eventsPageBanner/EventsPageBanner.tsx
  yarn.lock
Labels: Security, size/XS

#1313 WEBREF-20 ♻️ Refactor eventDateFilter to hooks and typescript
  package.json
  src/features/events/filters/eventDateFilter/eventDateFilter.styles.ts
  src/features/events/filters/eventDateFilter/eventDateFilter.tsx
  src/features/events/filters/eventDateFilter/eventDateFilter.types.ts
  src/features/events/filters/eventDateFilter/index.ts
  src/types/generic.ts
  src/types/index.ts
  yarn.lock
Labels: Refactoring, size/L

#1289 WEBREF-21 ♻️ Refactor EventDropdownFilter component to use hooks
  package.json
  src/features/events/components/eventsFilters.js
  src/features/events/filters/eventDropdownFilter.js
  src/features/help/components/dropDown.js
  yarn.lock
Labels: Refactoring, size/L

#1303 WEBNEW-31 ✨ Create AppPromotionCard
  src/features/events/components/appPromotionCard.tsx
  src/features/events/components/groupedEventsCard.js
  src/features/events/index.js
  src/features/events/tests/__snapshots__/groupedEventsCard.test.js.snap
  src/features/events/tests/appPromotionCard.test.tsx
  src/features/events/tests/groupedEventsCard.test.js
Labels: Event, size/L

#1331 WEBNEW-69 🔥 Remove parade applications component
  src/features/homepage/components/paradeApplications/index.js
  src/pages/index.js
Labels: Parade Groups, size/L

#1266 WEBREF-17 ♻️ Refactor NewsContainer to use hooks and add tests
  src/components/filterButton/index.js
  src/components/filterButton/index.test.js
  src/features/blog/components/newsCard/__snapshots__/index.test.js.snap
  src/features/blog/components/newsCard/index.js
  src/features/blog/components/newsCard/index.test.js
  src/features/blog/containers/newsContainer/__snapshots__/index.test.js.snap
  src/features/blog/containers/newsContainer/index.js
  src/features/blog/containers/newsContainer/index.test.js
Labels: Refactoring, size/L

#1345 WEBNEW-74 ♻️ Update redirects for campaign
  static/_redirects
Labels: Homepage, size/XS

#1344 WEBNEW-75 ♻️ Update the menu
  src/components/navigation/nav/index.js
Labels: Homepage, size/XS

#1346 WEBNEW-76 ♻️ Update footer with new hashtag
  src/components/footer/index.js
Labels: Homepage, size/XS
