Repository PrideInLondon/pride-london-web, pull requests merged in 2021-01, with the labels that each got.

#1828 WEBNEW-213 ✨ Blog render methods
  gatsby-config.js
  src/components/image/Image.tsx
  src/components/image/Image.types.ts
  src/components/image/index.ts
  src/components/quote/Quote.tsx
  src/components/quote/index.ts
  src/components/renderMethods.tsx
  src/components/richText/RichText.stories.tsx
  src/components/richText/RichText.styles.ts
  src/components/richText/RichText.test.tsx
  src/components/richText/RichText.tsx
  src/components/richText/RichText.types.ts
  src/components/richText/__mocks__/index.ts
  src/components/richText/index.ts
  src/components/richText/renderMethods.test.ts
  src/components/richText/renderMethods.tsx
  src/components/talentProfile/TalentProfile.tsx
  src/fifty-two/FiftyTwoPage.tsx
  src/fifty-two/entry/AboutTheArtwork.tsx
  src/utils/number-utils.test.ts
  src/utils/number-utils.ts
Labels: Blog, New Component, New Feature, size/XL

#1825 WEBNEW-209 ✨ Image component
  src/components/image/Image.stories.tsx
  src/components/image/Image.styles.ts
  src/components/image/Image.test.tsx
  src/components/image/Image.tsx
  src/components/image/Image.types.ts
  src/components/richText/RichText.types.ts
  src/components/richText/__mocks__/index.ts
  src/components/richText/renderMethods.tsx
Labels: New Component, size/M

#1856 WEBNEW-227 💄 Video component improved a11y and UX
  src/components/playButton/PlayButton.styles.tsx
  src/components/playButton/PlayButton.tsx
  src/components/playButton/PlayButton.types.ts
  src/components/video/Video.styles.ts
  src/components/video/Video.test.tsx
  src/components/video/Video.tsx
Labels: Bug, size/L

#1880 WEBNEW-214 ✨ Blog article template page
  gatsby-node.esm.js
  src/blog/article/BlogArticlePage.styles.ts
  src/blog/article/BlogArticlePage.tsx
  src/blog/article/BlogArticlePage.types.ts
  src/components/quote/Quote.styles.tsx
  src/components/quote/Quote.tsx
  src/components/richText/RichText.styles.ts
  src/components/richText/RichText.tsx
  src/components/richText/RichText.types.ts
  src/components/richText/renderMethods.tsx
  src/components/rippedSection/RippedSection.styles.tsx
  src/components/rippedSection/RippedSection.types.ts
  src/components/talentProfile/TalentProfile.types.ts
  src/components/wrapper/index.ts
  src/layout/Layout.styles.js
  src/theme/breakpoints.ts
  src/utils/style-utils.ts
Labels: Blog, size/L
