Repository PrideInLondon/pride-london-web, pull requests merged in 2022-04, with the labels that each got.

#2037 WEBREF-123 :lipstick: Alter zoom and location-centre for Parade map view
  src/parade/ParadeMapPage.js
Labels: size/XS

#2038 WEBREF-123 :lipstick: WEBREF-123 :lipstick: Remove parameter that bre…
  src/parade/ParadeMapPage.js
Labels: size/XS

#2039 WEBNEW-269 :fire: Remove CTAs, change text and ctas
  src/layout/navigation/Navigation.tsx
  src/parade/ParadeMapPage.js
Labels: size/M

#2041 WEBNEW-269 :fire: Remove submenu
  src/layout/navigation/Navigation.tsx
Labels: size/M

#2042 WEBNEW-269 :sparkles: Revert "Merge pull request #2041 from PrideInLo…
  src/layout/navigation/Navigation.tsx
Labels: size/M

#2045 Website audit remove pages
  gatsby-node.esm.js
  src/campaigns/youMeUsWe/ActsOfAllyshipBox.tsx
  src/campaigns/youMeUsWe/ActsOfAllyshipHeading.tsx
  src/campaigns/youMeUsWe/ActsOfAllyshipSection.styles.ts
  src/campaigns/youMeUsWe/ActsOfAllyshipSection.tsx
  src/campaigns/youMeUsWe/BeThereForYourCommunitySection.styles.ts
  src/campaigns/youMeUsWe/BeThereForYourCommunitySection.tsx
  src/campaigns/youMeUsWe/CTABox.tsx
  src/campaigns/youMeUsWe/CTABox.types.ts
  src/campaigns/youMeUsWe/CelebrateYourCommunitySection.styles.ts
  src/campaigns/youMeUsWe/CelebrateYourCommunitySection.tsx
  src/campaigns/youMeUsWe/DonateToYourCommunitySection.styles.ts
  src/campaigns/youMeUsWe/DonateToYourCommunitySection.tsx
  src/campaigns/youMeUsWe/ForEveryKindSection.styles.ts
  src/campaigns/youMeUsWe/ForEveryKindSection.tsx
  src/campaigns/youMeUsWe/Mark.tsx
  src/campaigns/youMeUsWe/PrideInLockdownSection.styles.ts
  src/campaigns/youMeUsWe/PrideInLockdownSection.tsx
  src/campaigns/youMeUsWe/YouMeUsWePage.styles.tsx
  src/campaigns/youMeUsWe/YouMeUsWePage.tsx
  src/campaigns/youMeUsWe/YouMeUsWePageHelmet.tsx
  src/campaigns/youMeUsWe/YouMeUseWePage.types.ts
  src/campaigns/youMeUsWe/assets/banner/Mark.tsx
  src/campaigns/youMeUsWe/assets/banner/background.jpg
  src/campaigns/youMeUsWe/assets/different.jpg
  src/campaigns/youMeUsWe/assets/mark.png
  src/campaigns/youMeUsWe/assets/rallying.jpg
  src/campaigns/youMeUsWe/assets/sunshine.jpg
  src/campaigns/youMeUsWe/assets/ymuw-meta.jpg
  src/campaigns/youMeUsWe/assets/ymuw.jpg
  src/campaigns/youMeUsWe/share.tsx
  src/fifty-two/AgeVerification.tsx
  src/fifty-two/FiftyTwoPage.styles.ts
  src/fifty-two/FiftyTwoPage.tsx
  src/fifty-two/FiftyTwoPage.types.ts
  src/fifty-two/entry/AboutTheArtwork.tsx
  src/fifty-two/entry/FiftyTwoEntryPage.styles.ts
  src/fifty-two/entry/FiftyTwoEntryPage.tsx
  src/fifty-two/entry/FiftyTwoEntryPage.types.ts
  src/fifty-two/helpers.ts
  src/fifty-two/meta.jpg
  src/layout/navigation/Navigation.tsx
  src/pages/about-us/campaigns/you-me-us-we.js
  src/pages/fifty-two.js
  static/_redirects
Labels: size/XXL

#2046 WEBNEW-271 :sparkles: Add redirects for rbl
  static/_redirects
Labels: size/XS
