Repository PrideInLondon/pride-london-web, pull requests merged in 2023-06, with the labels that each got.

#2090 Various stashed changes
  src/components/banner/BannerSubtitle.styles.js
  src/components/footer/Footer.styles.tsx
  src/components/footer/Footer.tsx
  src/homepage/HomePage.js
  src/homepage/SocialSection.js
  src/homepage/SocialWall.js
  src/homepage/SocialWall.styles.js
  src/homepage/SocialWallSectionHeader.js
  src/layout/navigation/Navigation.tsx
  src/pages/parade/pil2023.js
  src/parade/PiL2023Page.js
  src/parade/index.js
  yarn.lock
Labels: size/XXL

#2091 Fixed built issues
  src/components/footer/Footer.tsx
  src/homepage/HomePage.js
  src/homepage/SocialSection.js
  src/homepage/SocialWall.js
  src/homepage/SocialWall.styles.js
  src/homepage/SocialWallSectionHeader.js
  src/layout/navigation/Navigation.tsx
  yarn.lock
Labels: size/XXL

#2092 Dev early release
  src/constants.js
  src/sponsors/PartnersPage.tsx
Labels: size/S

#2093 Update leicester square stage url
  src/layout/navigation/Navigation.tsx
Labels: size/XS

#2094 Update sustainability
  .github/CODEOWNERS
  src/components/banner/BannerSubtitle.styles.js
  src/homepage/HomePage.js
  src/layout/navigation/Navigation.tsx
Labels: size/S

#2095 Linting
  .github/CODEOWNERS
  src/homepage/HomePage.js
Labels: size/XS

#2096 Dev early release
  src/homepage/AnnouncementList.js
  src/homepage/AnnouncementListCard.js
  src/homepage/AnnouncementListCard.styles.js
  src/homepage/AnnouncementListHeader.js
  src/homepage/Announcements.js
  src/homepage/HomePage.js
Labels: size/L

#2097 Parade 2023 redirection
  src/homepage/HomePage.js
  src/layout/navigation/Navigation.tsx
  static/_redirects
Labels: size/XS

#2098 Dev early release
  src/constants.js
  src/events/EventsDateFilters.js
  src/events/EventsPage.js
  src/events/EventsPage.test.js
  src/events/EventsPageFilters.js
  src/events/EventsPageFilters.styles.js
  src/events/GroupedEventsCards.test.js
  src/pages/parade/groups.js
  src/parade/ParadeGroupsPage.js
Labels: size/L

#2099 Update header
  src/layout/navigation/Navigation.tsx
Labels: size/XS

#2100 Test PR Build
  src/components/icons/snapchat.js
  src/components/icons/tiktok.js
  src/layout/navigation/Navigation.tsx
  src/pages/parade/groups.js
  src/parade/ParadeGroup.js
  src/parade/ParadeGroups.js
  src/parade/ParadeGroups.test.tsx
Labels: size/L

#2101 Parade Group filter update
  src/pages/parade/groups.js
Labels: size/XS

#2103 Dev early release
  src/layout/navigation/Navigation.tsx
  src/pages/parade/groups.js
  src/parade/ParadeGroups.js
Labels: size/M

#2104 Updated parade URL
  src/homepage/HomePage.js
  src/layout/navigation/Navigation.tsx
Labels: size/XS

#2105 Dev early release
  src/layout/navigation/Navigation.tsx
Labels: size/XS

#2107 Added parade group description
  src/parade/ParadeGroup.js
  src/parade/ParadeGroup.styles.js
  src/parade/ParadeGroups.js
Labels: size/M

#2109 Dev early release 2
  src/parade/ParadeGroupsPage.js
Labels: size/XS

#2110 text update
  src/parade/ParadeGroupsPage.js
Labels: size/XS

#2111 Dev early release 2
  src/layout/Layout.js
  src/parade/ParadeGroup.js
Labels: size/XS

#2112 Dev early release 2
  src/pages/parade/groups.js
Labels: size/XS
